import { Product } from "@/types";
import { getRandomGummiFriends } from "../mock-users";


export const ART_PRODUCTS: Product[] = [
  // ─── 1. Abstract Brush Stroke Print ─────────────────
  {
    id: "art-1",
    title: "Abstract Brush Stroke Print No. 01",
    brand: "The Poster Club",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80",
      alt: "Bold abstract brush stroke artwork in warm tones",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Bold abstract brush stroke artwork in warm tones" },
      { url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80", alt: "Abstract print styled on gallery wall" },
    ],
    price: { min: 4500, max: 8500, currency: "USD" },
    rating: { average: 4.7, count: 892 },
    buyUrl: "https://theposterclub.com",
    topFeatures: ["Museum-quality giclée print", "Acid-free 230gsm paper", "Available in 3 sizes", "Unframed"],
    description: "A sweeping composition of gestural brush strokes that brings energy to any room. Printed on heavyweight archival paper with pigment-based inks for lasting color fidelity. Each print ships rolled in a protective tube.",
    aspectRatio: 1.42,
    gummis: 14500,
    shares: 1595,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 2. Botanical Illustration ──────────────────────
  {
    id: "art-2",
    title: "Eucalyptus Branch Botanical Illustration",
    brand: "Juniper Print Shop",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80",
      alt: "Delicate eucalyptus branch botanical illustration",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Delicate eucalyptus branch botanical illustration" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Botanical print in oak frame on shelf" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Close-up detail of botanical linework" },
    ],
    price: { min: 3800, max: 7200, currency: "USD" },
    rating: { average: 4.8, count: 1345 },
    buyUrl: "https://juniperprintshop.com",
    topFeatures: ["Hand-drawn original artwork", "Matte finish", "100% cotton rag paper", "Ships flat"],
    description: "A graceful eucalyptus branch rendered in soft sage and forest greens with precise botanical detail. The understated palette makes this a timeless addition to bedrooms, bathrooms, or living spaces. Printed on cotton rag paper for a museum-quality feel.",
    aspectRatio: 1.50,
    gummis: 18000,
    shares: 2160,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 3. Coastal Photography Print ───────────────────
  {
    id: "art-3",
    title: "Pacific Coast Aerial Photography Print",
    brand: "Minted",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
      alt: "Aerial view of turquoise ocean meeting rocky coast",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Aerial view of turquoise ocean meeting rocky coast" },
      { url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=1200&q=80", alt: "Wide coastal landscape at golden hour" },
    ],
    price: { min: 5800, max: 18000, currency: "USD" },
    rating: { average: 4.6, count: 678 },
    buyUrl: "https://minted.com",
    topFeatures: ["Limited edition of 250", "Signed by photographer", "Lustre photo paper", "Custom framing available"],
    description: "A breathtaking aerial perspective capturing where the Pacific meets volcanic coastline. The jewel-tone waters and dramatic rock formations create a piece that transforms any wall into a window. Available in limited quantities with a certificate of authenticity.",
    aspectRatio: 0.75,
    gummis: 32000,
    shares: 4160,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 4. Bauhaus Exhibition Poster ───────────────────
  {
    id: "art-4",
    title: "Bauhaus Exhibition Poster — Geometric Composition",
    brand: "King & McGaw",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=600&q=80",
      alt: "Bold Bauhaus-style geometric poster with primary colors",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Bold Bauhaus-style geometric poster with primary colors" },
      { url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1200&q=80", alt: "Exhibition poster framed on concrete wall" },
      { url: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&q=80", alt: "Detail of typography and geometric forms" },
    ],
    price: { min: 3500, max: 6500, currency: "USD" },
    rating: { average: 4.5, count: 2340 },
    buyUrl: "https://kingandmcgaw.com",
    topFeatures: ["Officially licensed reproduction", "Heavyweight 250gsm paper", "Vivid archival inks", "Multiple sizes"],
    description: "A faithful reproduction of a 1923 Bauhaus exhibition poster featuring bold geometric forms in red, yellow, and blue. The iconic design brings mid-century modernist energy to contemporary spaces. Printed on heavyweight paper with museum-grade inks.",
    aspectRatio: 1.45,
    gummis: 28000,
    shares: 3360,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 5. Line Art Portrait ───────────────────────────
  {
    id: "art-5",
    title: "Continuous Line Art Portrait — Woman in Repose",
    brand: "Desenio",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&q=80",
      alt: "Minimal single-line drawing of a woman in profile",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&q=80", alt: "Minimal single-line drawing of a woman in profile" },
      { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1200&q=80", alt: "Line art print in slim black frame" },
    ],
    price: { min: 2200, max: 4500, currency: "USD" },
    rating: { average: 4.6, count: 3120 },
    buyUrl: "https://desenio.com",
    topFeatures: ["Minimalist Scandinavian design", "Premium matte paper", "Available unframed or framed", "Fast delivery"],
    description: "An elegant continuous-line drawing that captures the quiet beauty of the human form with just a single unbroken stroke. The clean white background and black ink create striking contrast that pairs with any interior style. A bestselling Desenio original.",
    aspectRatio: 1.35,
    gummis: 11500,
    shares: 1380,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 6. Minimalist Typography Print ─────────────────
  {
    id: "art-6",
    title: "Minimalist Typography Print — 'Be Still'",
    brand: "Paper Collective",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&q=80",
      alt: "Minimalist black and white typography art print",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80", alt: "Minimalist black and white typography art print" },
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Typography print styled on bedroom wall" },
    ],
    price: { min: 3200, max: 5800, currency: "USD" },
    rating: { average: 4.4, count: 956 },
    buyUrl: "https://papercollective.com",
    topFeatures: ["FSC-certified paper", "Soy-based inks", "Danish design studio", "Pairs well in gallery walls"],
    description: "A serene typographic composition that brings calm to any space with its carefully chosen words and balanced layout. Printed in Copenhagen on sustainably sourced paper with eco-friendly soy-based inks. Part of Paper Collective's mindfulness series.",
    aspectRatio: 1.40,
    gummis: 9500,
    shares: 1140,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 7. Japanese Woodblock Reproduction ─────────────
  {
    id: "art-7",
    title: "Hokusai 'Great Wave' Woodblock Reproduction",
    brand: "King & McGaw",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80",
      alt: "Japanese woodblock print reproduction of the Great Wave",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Japanese woodblock print reproduction of the Great Wave" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Woodblock print in traditional frame" },
    ],
    price: { min: 2800, max: 9500, currency: "USD" },
    rating: { average: 4.8, count: 4230 },
    buyUrl: "https://kingandmcgaw.com",
    topFeatures: ["Archival museum reproduction", "Textured washi-style paper", "Vivid period-accurate colors", "Certificate of authenticity"],
    description: "An exquisite reproduction of Katsushika Hokusai's iconic 1831 woodblock masterpiece, printed on textured paper that evokes traditional washi. The dynamic composition and indigo palette remain as captivating as ever. A timeless statement piece for any collector.",
    aspectRatio: 0.72,
    gummis: 55000,
    shares: 6600,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 8. Figure Drawing Study ────────────────────────
  {
    id: "art-8",
    title: "Charcoal Figure Drawing Study No. 3",
    brand: "Tappan Collective",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=600&q=80",
      alt: "Expressive charcoal figure drawing on cream paper",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Expressive charcoal figure drawing on cream paper" },
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Figure study framed in floating white frame" },
    ],
    price: { min: 38000, max: 65000, currency: "USD" },
    rating: { average: 4.9, count: 87 },
    buyUrl: "https://tappancollective.com",
    topFeatures: ["Original artwork", "Signed and numbered", "Emerging artist", "Gallery-quality framing available"],
    description: "A bold yet intimate charcoal study that captures the fluidity of the human form in confident, gestural marks. Created by an emerging Brooklyn-based artist whose work explores the tension between movement and stillness. Each piece is a unique original.",
    aspectRatio: 1.50,
    gummis: 4200,
    shares: 504,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 9. Landscape Photograph ────────────────────────
  {
    id: "art-9",
    title: "Dolomites at Dawn — Limited Edition Photograph",
    brand: "Sonic Editions",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=600&q=80",
      alt: "Misty mountain peaks of the Dolomites at sunrise",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Misty mountain peaks of the Dolomites at sunrise" },
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Mountain landscape in gallery setting" },
    ],
    price: { min: 15000, max: 45000, currency: "USD" },
    rating: { average: 4.7, count: 234 },
    buyUrl: "https://soniceditions.com",
    topFeatures: ["Edition of 150 worldwide", "Archival pigment print", "Framed in solid ash", "UV-protective glass"],
    description: "The Dolomites emerge from a sea of morning mist in this ethereal landscape captured at golden hour. Printed on Hahnemühle fine art paper and framed in sustainably sourced ash with UV-protective glass. A collector's piece that brings the grandeur of nature indoors.",
    aspectRatio: 0.75,
    gummis: 22000,
    shares: 2640,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 10. Vintage Travel Poster ──────────────────────
  {
    id: "art-10",
    title: "Vintage Amalfi Coast Travel Poster",
    brand: "Desenio",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=600&q=80",
      alt: "Retro-style travel poster depicting the Amalfi Coast",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1200&q=80", alt: "Retro-style travel poster depicting the Amalfi Coast" },
      { url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=1200&q=80", alt: "Travel poster in gold frame on shelf" },
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Detail of vintage illustration and typography" },
    ],
    price: { min: 1800, max: 3600, currency: "USD" },
    rating: { average: 4.5, count: 4780 },
    buyUrl: "https://desenio.com",
    topFeatures: ["Retro illustration style", "Thick 200gsm paper", "Vibrant color palette", "Great for gallery walls"],
    description: "Transport yourself to the sun-drenched Italian coast with this art deco-inspired travel poster featuring pastel buildings and azure waters. The nostalgic illustration style and warm color palette evoke the golden age of travel. A perennial bestseller.",
    aspectRatio: 1.50,
    gummis: 21000,
    shares: 2520,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 11. Contemporary Sculpture ─────────────────────
  {
    id: "art-11",
    title: "Abstract Form Ceramic Sculpture",
    brand: "Tappan Collective",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&q=80",
      alt: "Organic form ceramic sculpture in matte white glaze",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Organic form ceramic sculpture in matte white glaze" },
      { url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80", alt: "Sculpture detail showing hand-finished texture" },
    ],
    price: { min: 42000, max: 85000, currency: "USD" },
    rating: { average: 4.8, count: 62 },
    buyUrl: "https://tappancollective.com",
    topFeatures: ["Handcrafted one-of-a-kind", "High-fire stoneware", "Matte glaze finish", "Signed by artist"],
    description: "A striking sculptural form that balances organic curves with architectural presence, hand-built from high-fire stoneware. The velvety matte white glaze catches light beautifully throughout the day. Each piece is unique, shaped by the artist's hands in her Brooklyn studio.",
    aspectRatio: 0.85,
    gummis: 3800,
    shares: 456,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 12. Ceramic Art Object ─────────────────────────
  {
    id: "art-12",
    title: "Hand-Thrown Ceramic Vessel — Earth Tones",
    brand: "Artfully Walls",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80",
      alt: "Textured ceramic vessel in warm earth tones",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Textured ceramic vessel in warm earth tones" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Ceramic vessel styled on wooden console" },
    ],
    price: { min: 12000, max: 22000, currency: "USD" },
    rating: { average: 4.6, count: 189 },
    buyUrl: "https://artfullywalls.com",
    topFeatures: ["Wheel-thrown stoneware", "Food-safe glaze", "Reactive glaze variation", "Approx. 8 inches tall"],
    description: "A beautifully imperfect hand-thrown vessel featuring a reactive glaze that creates unique earth-tone patterns on every piece. The organic silhouette works equally well as a standalone art object or a functional vase. Made in a small-batch ceramics studio in Joshua Tree.",
    aspectRatio: 0.90,
    gummis: 5500,
    shares: 660,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 13. Photography Book ───────────────────────────
  {
    id: "art-13",
    title: "Magnum Photos — 'Contact Sheets' Coffee Table Book",
    brand: "Artifact Uprising",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80",
      alt: "Heavyweight photography book on marble surface",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Heavyweight photography book on marble surface" },
      { url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=1200&q=80", alt: "Open spread showing iconic contact sheets" },
    ],
    price: { min: 6500, max: 6500, currency: "USD" },
    rating: { average: 4.9, count: 1560 },
    buyUrl: "https://artifactuprising.com",
    topFeatures: ["320 pages, hardcover", "Linen cloth binding", "Tritone printing", "Includes 100+ photographers"],
    description: "A definitive collection of contact sheets from Magnum's legendary photographers, revealing the creative process behind iconic images. The oversized format and tritone printing reproduce each frame with stunning fidelity. An essential volume for any photography lover's library.",
    aspectRatio: 0.80,
    gummis: 38000,
    shares: 4560,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 14. Gallery Frame ──────────────────────────────
  {
    id: "art-14",
    title: "Modern Gallery Frame — Solid Oak",
    brand: "Framebridge",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80",
      alt: "Clean solid oak gallery frame with white mat",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Clean solid oak gallery frame with white mat" },
      { url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1200&q=80", alt: "Oak frame displayed on light wall" },
    ],
    price: { min: 6900, max: 18900, currency: "USD" },
    rating: { average: 4.7, count: 3450 },
    buyUrl: "https://framebridge.com",
    topFeatures: ["Sustainably sourced white oak", "Acid-free mat included", "UV-protective acrylic glazing", "Ready to hang"],
    description: "A beautifully simple frame crafted from solid white oak with a natural finish that showcases the grain. Includes an acid-free mat and UV-protective acrylic to keep your artwork safe for decades. Arrives ready to hang with all hardware included.",
    aspectRatio: 1.30,
    gummis: 16000,
    shares: 1920,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 15. Art Print Set ──────────────────────────────
  {
    id: "art-15",
    title: "Curated Gallery Wall Set — 5 Prints",
    brand: "Desenio",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80",
      alt: "Five coordinated art prints arranged as a gallery wall",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&q=80", alt: "Five coordinated art prints arranged as a gallery wall" },
      { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1200&q=80", alt: "Gallery wall set in living room setting" },
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Close-up of individual prints from the set" },
    ],
    price: { min: 5500, max: 8900, currency: "USD" },
    rating: { average: 4.5, count: 2870 },
    buyUrl: "https://desenio.com",
    topFeatures: ["5 complementary prints", "Mix of sizes included", "Hanging template provided", "Styled by in-house team"],
    description: "Take the guesswork out of gallery walls with this expertly curated set of five complementary prints in a mix of abstract, botanical, and photographic styles. Includes a hanging template for effortless installation. An instant room transformation.",
    aspectRatio: 0.85,
    gummis: 19500,
    shares: 2340,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 16. Mixed Media Collage ────────────────────────
  {
    id: "art-16",
    title: "Mixed Media Collage — 'Urban Layers'",
    brand: "Tappan Collective",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80",
      alt: "Layered mixed media collage with paper and paint",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80", alt: "Layered mixed media collage with paper and paint" },
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Detail view showing textural layers" },
    ],
    price: { min: 55000, max: 120000, currency: "USD" },
    rating: { average: 4.8, count: 54 },
    buyUrl: "https://tappancollective.com",
    topFeatures: ["Original mixed media work", "Signed and dated", "Museum-wrapped canvas", "Certificate of authenticity"],
    description: "An original mixed media work combining vintage ephemera, acrylic paint, and handmade paper in a rich urban palette. The complex layering rewards close viewing with surprising details and textures. Created by an LA-based artist whose work has been featured in Architectural Digest.",
    aspectRatio: 1.00,
    gummis: 6800,
    shares: 816,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 17. Geometric Print ────────────────────────────
  {
    id: "art-17",
    title: "Geometric Gradient Art Print — Emerald & Gold",
    brand: "Society6",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=600&q=80",
      alt: "Geometric gradient print in emerald green and gold",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Geometric gradient print in emerald green and gold" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Geometric print in home office setting" },
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Print edge detail showing paper texture" },
    ],
    price: { min: 2500, max: 6500, currency: "USD" },
    rating: { average: 4.3, count: 1890 },
    buyUrl: "https://society6.com",
    topFeatures: ["Vibrant dye-sub printing", "Natural white border", "Ships worldwide", "Artist profit share"],
    description: "A mesmerizing geometric composition where emerald facets dissolve into gold through a series of precise gradients. The jewel-tone palette brings warmth and sophistication to modern interiors. Each purchase supports the independent artist directly through Society6's profit-sharing model.",
    aspectRatio: 1.42,
    gummis: 12000,
    shares: 1440,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 18. Nature Macro Photograph ────────────────────
  {
    id: "art-18",
    title: "Monstera Leaf Macro — Fine Art Photograph",
    brand: "Lumas",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=600&q=80",
      alt: "Extreme close-up of monstera leaf showing cellular detail",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Extreme close-up of monstera leaf showing cellular detail" },
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Macro photograph in minimal white frame" },
    ],
    price: { min: 18000, max: 48000, currency: "USD" },
    rating: { average: 4.7, count: 312 },
    buyUrl: "https://lumas.com",
    topFeatures: ["Numbered edition of 75", "Diasec mounting available", "Museum-grade C-print", "Gallery provenance"],
    description: "An intimate macro study that reveals the architectural beauty hidden within a single monstera leaf. The rich green palette and cellular detail create an almost abstract composition. Printed as a museum-grade C-print with Diasec mounting option for a frameless gallery presentation.",
    aspectRatio: 1.35,
    gummis: 24000,
    shares: 2880,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 19. Architectural Photography ──────────────────
  {
    id: "art-19",
    title: "Brutalist Architecture — Concrete Geometry",
    brand: "Sonic Editions",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80",
      alt: "Dramatic black and white photograph of brutalist building",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Dramatic black and white photograph of brutalist building" },
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Architecture print in black aluminum frame" },
    ],
    price: { min: 12000, max: 32000, currency: "USD" },
    rating: { average: 4.6, count: 456 },
    buyUrl: "https://soniceditions.com",
    topFeatures: ["Silver gelatin print option", "Framed in anodized aluminum", "Edition of 200", "Archival quality"],
    description: "Raw concrete and bold geometry converge in this striking architectural photograph that celebrates brutalist design. The high-contrast black and white treatment emphasizes the interplay of light, shadow, and form. Available as a silver gelatin print for collectors seeking the ultimate photographic quality.",
    aspectRatio: 1.30,
    gummis: 20000,
    shares: 2400,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 20. Watercolor Landscape ───────────────────────
  {
    id: "art-20",
    title: "Abstract Watercolor Landscape — Horizon Study",
    brand: "Minted",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&q=80",
      alt: "Soft watercolor landscape with layered horizons",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1200&q=80", alt: "Soft watercolor landscape with layered horizons" },
      { url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=1200&q=80", alt: "Watercolor print in natural wood frame" },
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Detail of watercolor washes and pigment" },
    ],
    price: { min: 4200, max: 14500, currency: "USD" },
    rating: { average: 4.7, count: 890 },
    buyUrl: "https://minted.com",
    topFeatures: ["Independent artist design", "Custom sizing available", "Eco-friendly printing", "30-day returns"],
    description: "Layers of translucent watercolor washes create a dreamy landscape that hovers between abstraction and representation. The soft palette of dusty blues, warm greys, and blush evokes a peaceful twilight. Selected from Minted's community of independent artists through their design competition.",
    aspectRatio: 0.75,
    gummis: 13500,
    shares: 1620,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 21. Risograph Print ────────────────────────────
  {
    id: "art-21",
    title: "Risograph Print — 'Sunbathers' Two-Color",
    brand: "Atelier CPH",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=600&q=80",
      alt: "Two-color risograph print with bold shapes and textures",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Two-color risograph print with bold shapes and textures" },
      { url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80", alt: "Risograph print with visible ink texture" },
    ],
    price: { min: 2800, max: 4200, currency: "USD" },
    rating: { average: 4.4, count: 345 },
    buyUrl: "https://ateliercph.com",
    topFeatures: ["Printed on vintage Risograph", "Soy-based inks", "A3 format", "Slight variation per print"],
    description: "A playful two-color risograph print that celebrates summer leisure with bold, simplified forms and the characteristic grain of soy-based riso ink. The slight variation in each print makes every copy unique. Printed in Copenhagen on a lovingly maintained vintage Risograph machine.",
    aspectRatio: 1.42,
    gummis: 7200,
    shares: 864,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 22. Abstract Oil Painting Print ────────────────
  {
    id: "art-22",
    title: "Abstract Oil Study — Warm Terracotta Palette",
    brand: "Artfully Walls",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80",
      alt: "Warm abstract oil painting with terracotta and ochre tones",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Warm abstract oil painting with terracotta and ochre tones" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Abstract print in floating frame on console" },
    ],
    price: { min: 8500, max: 22000, currency: "USD" },
    rating: { average: 4.6, count: 567 },
    buyUrl: "https://artfullywalls.com",
    topFeatures: ["Giclée on canvas option", "Gallery-wrapped edges", "Rich color reproduction", "Interior designer favorite"],
    description: "Rich layers of terracotta, burnt sienna, and golden ochre create a warmth-filled abstract composition that anchors any room. The visible brushwork and textural quality are faithfully reproduced through giclée printing on fine art canvas. Curated by the Artfully Walls design team for spaces that need warmth.",
    aspectRatio: 1.20,
    gummis: 15000,
    shares: 1800,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 23. Black & White Photography ──────────────────
  {
    id: "art-23",
    title: "Cinematic Street Photography — 'Rainy Night'",
    brand: "Lumas",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80",
      alt: "Moody black and white street scene with rain reflections",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Moody black and white street scene with rain reflections" },
      { url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=1200&q=80", alt: "Print framed behind glass in dim room" },
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Detail showing tonal range and grain" },
    ],
    price: { min: 24000, max: 65000, currency: "USD" },
    rating: { average: 4.8, count: 178 },
    buyUrl: "https://lumas.com",
    topFeatures: ["Limited edition of 100", "Baryta fine art paper", "Anti-reflective museum glass", "Gallery representation"],
    description: "A cinematic moment frozen in silver — a solitary figure crosses a rain-slicked boulevard as city lights dissolve into liquid reflections. Printed on baryta fine art paper that delivers the tonal depth and silver-rich blacks of a traditional darkroom print. From Lumas' curated gallery of contemporary photography.",
    aspectRatio: 1.50,
    gummis: 45000,
    shares: 5400,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 24. Matisse-Style Cut-Out Print ────────────────
  {
    id: "art-24",
    title: "Paper Cut-Out Print — 'Blue Nude' Homage",
    brand: "The Poster Club",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80",
      alt: "Matisse-inspired blue cut-out art print",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Matisse-inspired blue cut-out art print" },
      { url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1200&q=80", alt: "Cut-out print styled with vase and books" },
    ],
    price: { min: 3800, max: 7200, currency: "USD" },
    rating: { average: 4.7, count: 2100 },
    buyUrl: "https://theposterclub.com",
    topFeatures: ["Exclusive artist collaboration", "Uncoated premium paper", "Vibrant ultramarine blue", "Scandinavian design"],
    description: "A contemporary homage to Matisse's paper cut-outs, featuring bold ultramarine forms against a warm cream background. The deceptively simple composition carries the joyful energy of the original gouache technique. An exclusive collaboration with a Copenhagen-based illustrator.",
    aspectRatio: 1.45,
    gummis: 17500,
    shares: 2100,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 25. Nature Photography — Forest ────────────────
  {
    id: "art-25",
    title: "Enchanted Forest — Large Format Photograph",
    brand: "Minted",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=600&q=80",
      alt: "Mystical forest scene with sunlight filtering through canopy",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&q=80", alt: "Mystical forest scene with sunlight filtering through canopy" },
      { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1200&q=80", alt: "Forest photograph in modern living room" },
    ],
    price: { min: 7500, max: 19500, currency: "USD" },
    rating: { average: 4.5, count: 445 },
    buyUrl: "https://minted.com",
    topFeatures: ["Up to 40x60 inch size", "Metallic paper option", "Independently photographed", "Foil-pressed signature"],
    description: "Shafts of morning light pierce a moss-draped forest canopy in this immersive large-format photograph. The sense of depth and atmosphere is extraordinary, drawing viewers into the scene. Available in sizes up to 40x60 inches with a metallic paper option that adds luminosity.",
    aspectRatio: 1.33,
    gummis: 10500,
    shares: 1260,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 26. Mid-Century Modern Print ───────────────────
  {
    id: "art-26",
    title: "Mid-Century Atomic Starburst Print",
    brand: "Society6",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=600&q=80",
      alt: "Retro mid-century modern atomic starburst design in mustard and teal",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80", alt: "Retro mid-century modern atomic starburst design in mustard and teal" },
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Mid-century print above credenza" },
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Print detail showing clean vector lines" },
    ],
    price: { min: 1800, max: 4500, currency: "USD" },
    rating: { average: 4.2, count: 3670 },
    buyUrl: "https://society6.com",
    topFeatures: ["Multiple format options", "Framed or unframed", "Vibrant fade-resistant inks", "Supports independent artist"],
    description: "Channel the optimistic energy of the Space Age with this retro-modern starburst print in a punchy mustard and teal palette. The clean lines and bold forms are a natural fit for mid-century-inspired interiors. Available as a print, canvas, or even a throw pillow from Society6.",
    aspectRatio: 1.00,
    gummis: 8500,
    shares: 1020,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 27. Ocean Photography ──────────────────────────
  {
    id: "art-27",
    title: "Abstract Ocean — Slow Exposure Seascape",
    brand: "Sonic Editions",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
      alt: "Long exposure seascape with silky water and pastel sky",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Long exposure seascape with silky water and pastel sky" },
      { url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80", alt: "Seascape print in bedroom setting" },
    ],
    price: { min: 9500, max: 28000, currency: "USD" },
    rating: { average: 4.7, count: 289 },
    buyUrl: "https://soniceditions.com",
    topFeatures: ["120-second exposure technique", "Hahnemühle Photo Rag", "Framed in brushed steel", "Edition of 175"],
    description: "A two-minute exposure transforms the restless sea into a dreamlike plane of liquid silk beneath a gradient sky. The meditative quality of this image brings an instant sense of calm to any room. Printed on Hahnemühle Photo Rag and framed in brushed stainless steel.",
    aspectRatio: 0.70,
    gummis: 26000,
    shares: 3120,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 28. Sculptural Wall Object ─────────────────────
  {
    id: "art-28",
    title: "Woven Fiber Wall Sculpture — Natural Jute",
    brand: "IKEA Art Event",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=600&q=80",
      alt: "Textured woven jute wall sculpture with organic form",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Textured woven jute wall sculpture with organic form" },
      { url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80", alt: "Fiber sculpture mounted on white wall" },
    ],
    price: { min: 4900, max: 4900, currency: "USD" },
    rating: { average: 4.3, count: 780 },
    buyUrl: "https://ikea.com",
    topFeatures: ["Limited IKEA Art Event edition", "Handwoven natural jute", "Approx. 24 inches diameter", "Mounting hardware included"],
    description: "A striking hand-woven wall sculpture that adds organic texture and dimension to any space. Created from natural jute fibers as part of IKEA's annual Art Event collaboration with contemporary artists. The circular form and earthy tones complement both minimalist and bohemian interiors.",
    aspectRatio: 1.00,
    gummis: 14000,
    shares: 1680,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 29. Custom Pet Portrait ────────────────────────
  {
    id: "art-29",
    title: "Custom Digital Pet Portrait — Painterly Style",
    brand: "Minted",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=600&q=80",
      alt: "Custom digital pet portrait with painterly brushstrokes",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&q=80", alt: "Custom digital pet portrait with painterly brushstrokes" },
      { url: "https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200&q=80", alt: "Pet portrait in gold frame on mantle" },
      { url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80", alt: "Detail showing digital brushwork texture" },
    ],
    price: { min: 12000, max: 20000, currency: "USD" },
    rating: { average: 4.9, count: 2340 },
    buyUrl: "https://minted.com",
    topFeatures: ["Custom from your photo", "Digital illustration by artist", "Multiple background options", "Rush delivery available"],
    description: "Turn your beloved pet into a work of art with this custom digital portrait rendered in a rich, painterly style by a Minted artist. Simply upload your favorite photo and receive a stunning illustration. The perfect sentimental gift for any pet lover.",
    aspectRatio: 1.30,
    gummis: 23000,
    shares: 2760,
    gummiedByFriends: getRandomGummiFriends(),
  },
  // ─── 30. Oversized Abstract Canvas ──────────────────
  {
    id: "art-30",
    title: "Oversized Abstract Canvas — 'Quietude' Diptych",
    brand: "Tappan Collective",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80",
      alt: "Large-scale abstract diptych in soft neutrals and blush",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=1200&q=80", alt: "Large-scale abstract diptych in soft neutrals and blush" },
      { url: "https://images.unsplash.com/photo-1579541814924-49fef17c5be5?w=1200&q=80", alt: "Diptych installed above modern sofa" },
    ],
    price: { min: 180000, max: 350000, currency: "USD" },
    rating: { average: 4.9, count: 52 },
    buyUrl: "https://tappancollective.com",
    topFeatures: ["Two-panel diptych", "Original acrylic on canvas", "60x80 inches total", "White glove delivery included"],
    description: "A commanding two-panel abstract work that envelops a room in soft washes of ivory, blush, and warm grey. The generous scale and meditative palette create an atmosphere of quiet luxury. Includes white-glove delivery and installation in select metropolitan areas.",
    aspectRatio: 0.65,
    gummis: 5200,
    shares: 624,
    gummiedByFriends: getRandomGummiFriends(),
  },
];
