import { Product } from "@/types";
import { getRandomGumiFriends } from "../mock-users";

export const BOOKS_STATIONERY_PRODUCTS: Product[] = [
  {
    id: "books-1",
    title: "The Art Book - Revised Edition",
    brand: "Phaidon",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80",
      alt: "Large format art book with colorful cover on a wooden table",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1200&q=80", alt: "The Art Book cover detail" },
      { url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&q=80", alt: "The Art Book open spread showing paintings" },
      { url: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1200&q=80", alt: "The Art Book on a coffee table" },
    ],
    price: { min: 4900, max: 6500, currency: "USD" },
    rating: { average: 4.8, count: 3420 },
    buyUrl: "https://phaidon.com/the-art-book",
    topFeatures: [
      "Over 600 artists from medieval to contemporary",
      "A-to-Z format for easy browsing",
      "Full-color reproductions throughout",
      "Iconic Phaidon reference title",
    ],
    description: "The definitive A-to-Z guide to 600 great artists spanning medieval to contemporary art. Each entry features a full-page color reproduction and a concise text placing the work in its historical context.",
    aspectRatio: 1.35,
    gumis: 62000,
    shares: 4960,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-2",
    title: "Hardcover Linen Travel Journal",
    brand: "Midori",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80",
      alt: "Linen-bound travel journal with pen on a map",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200&q=80", alt: "Travel journal cover close-up" },
      { url: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1200&q=80", alt: "Travel journal open with handwritten notes" },
    ],
    price: { min: 2800, max: 3600, currency: "USD" },
    rating: { average: 4.7, count: 1890 },
    buyUrl: "https://midori-japan.co.jp/travel-journal",
    topFeatures: [
      "Refillable traveler's notebook system",
      "Genuine linen hardcover",
      "Lay-flat binding for comfortable writing",
      "Includes brass closure clasp",
    ],
    description: "A beautifully crafted refillable travel journal wrapped in natural linen. The lay-flat binding and premium Midori MD paper make it a joy to write in whether you're sketching cityscapes or jotting down travel notes.",
    aspectRatio: 0.75,
    gumis: 28000,
    shares: 2240,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-3",
    title: "AL Sport Brass Fountain Pen",
    brand: "Kaweco",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80",
      alt: "Brass fountain pen with cap resting on a leather notebook",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1200&q=80", alt: "Kaweco brass fountain pen close-up" },
      { url: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=1200&q=80", alt: "Kaweco pen writing sample on cream paper" },
    ],
    price: { min: 7500, max: 8500, currency: "USD" },
    rating: { average: 4.8, count: 2150 },
    buyUrl: "https://kaweco-pen.com/al-sport-brass",
    topFeatures: [
      "Solid brass body develops unique patina",
      "Fine steel nib for precise writing",
      "Compact pocket-sized design",
      "Compatible with standard ink cartridges",
      "Includes tin gift box",
    ],
    description: "The iconic Kaweco AL Sport in raw brass that develops a gorgeous patina over time. The compact pocket size and reliable steel nib make it the perfect everyday carry fountain pen for discerning writers.",
    aspectRatio: 0.65,
    gumis: 6800,
    shares: 544,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-4",
    title: "Botanical Wax Seal Kit",
    brand: "Rifle Paper Co.",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&q=80",
      alt: "Wax seal kit with brass stamp and sealing wax sticks",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=1200&q=80", alt: "Wax seal kit components laid out" },
      { url: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=1200&q=80", alt: "Sealed envelope with botanical wax impression" },
    ],
    price: { min: 3200, max: 4500, currency: "USD" },
    rating: { average: 4.6, count: 980 },
    buyUrl: "https://riflepaperco.com/botanical-wax-seal-kit",
    topFeatures: [
      "Hand-engraved brass seal stamp",
      "Includes 8 botanical sealing wax sticks",
      "Melting spoon with wooden handle",
      "Gift-ready presentation box",
    ],
    description: "An elegant wax seal kit featuring Rifle Paper Co.'s signature botanical motif engraved into a solid brass stamp. Includes richly pigmented sealing wax sticks in garden-inspired colors for beautiful correspondence.",
    aspectRatio: 1.0,
    gumis: 4200,
    shares: 336,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-5",
    title: "Linen Daily Planner 2026",
    brand: "Appointed",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&q=80",
      alt: "Linen-bound daily planner open on a desk with a pen",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=1200&q=80", alt: "Appointed linen planner cover" },
      { url: "https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=1200&q=80", alt: "Planner interior daily spread layout" },
      { url: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=1200&q=80", alt: "Planner with monthly overview pages" },
    ],
    price: { min: 4200, max: 5800, currency: "USD" },
    rating: { average: 4.7, count: 1540 },
    buyUrl: "https://appointed.co/daily-planner-2026",
    topFeatures: [
      "Bookcloth hardcover with gold foil details",
      "One page per day with hourly scheduling",
      "Monthly overview and goal-setting pages",
      "Smyth-sewn binding lays completely flat",
      "Made in the USA",
    ],
    description: "A thoughtfully designed daily planner wrapped in natural bookcloth with gold foil accents. Each day gets a full page with hourly time slots, notes sections, and priority lists to keep you organized year-round.",
    aspectRatio: 0.82,
    gumis: 22000,
    shares: 1760,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-6",
    title: "Vintage Rubber Stamp Collection",
    brand: "Papier",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=600&q=80",
      alt: "Collection of decorative rubber stamps in a wooden box",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=1200&q=80", alt: "Stamp collection detail" },
      { url: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=1200&q=80", alt: "Stamp impressions on kraft paper" },
    ],
    price: { min: 2400, max: 3800, currency: "USD" },
    rating: { average: 4.5, count: 620 },
    buyUrl: "https://papier.com/vintage-stamp-collection",
    topFeatures: [
      "Set of 12 hand-carved wooden stamps",
      "Botanical and typographic motifs",
      "Includes archival ink pad",
      "Wooden storage tray included",
    ],
    description: "A curated set of twelve hand-carved rubber stamps featuring vintage botanical illustrations and typographic elements. Perfect for adding artisan touches to journals, letters, and gift wrapping.",
    aspectRatio: 1.15,
    gumis: 3500,
    shares: 280,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-7",
    title: "Cities of the World Postcard Set",
    brand: "Monocle",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80",
      alt: "Set of illustrated postcards fanned out on a table",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=1200&q=80", alt: "Monocle postcard set overview" },
      { url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=80", alt: "Individual postcard illustration detail" },
    ],
    price: { min: 1800, max: 2500, currency: "USD" },
    rating: { average: 4.4, count: 870 },
    buyUrl: "https://monocle.com/cities-postcard-set",
    topFeatures: [
      "24 original city illustrations",
      "Heavyweight 350gsm cotton card stock",
      "Letterpress printed in small batches",
      "Packaged in a kraft paper sleeve",
    ],
    description: "Twenty-four letterpress-printed postcards featuring original illustrations of the world's most captivating cities. Printed on luxurious cotton card stock, each card is a miniature piece of art worth framing.",
    aspectRatio: 1.45,
    gumis: 5100,
    shares: 408,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-8",
    title: "In the Spirit of Travel",
    brand: "Assouline",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&q=80",
      alt: "Assouline luxury coffee table book with travel photography",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=80", alt: "Assouline book cover" },
      { url: "https://images.unsplash.com/photo-1522413452208-996ff3f3e740?w=1200&q=80", alt: "Book open to travel photography spread" },
      { url: "https://images.unsplash.com/photo-1528938102132-4a9276b8e320?w=1200&q=80", alt: "Book on coffee table in living room" },
    ],
    price: { min: 9500, max: 12500, currency: "USD" },
    rating: { average: 4.9, count: 1320 },
    buyUrl: "https://assouline.com/in-the-spirit-of-travel",
    topFeatures: [
      "Silk hardcover with hand-finished edges",
      "Over 200 archival photographs",
      "Signature Assouline presentation box",
      "Coffee table centerpiece format",
    ],
    description: "A stunning visual journey through the golden age of luxury travel, curated by Assouline. Over 200 archival photographs are printed on art-grade paper and bound in a silk hardcover with gilt-edged pages.",
    aspectRatio: 1.25,
    gumis: 45000,
    shares: 3600,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-9",
    title: "The Kinfolk Table Cookbook",
    brand: "Kinfolk",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1522413452208-996ff3f3e740?w=600&q=80",
      alt: "Kinfolk cookbook with minimalist cover on a linen cloth",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1522413452208-996ff3f3e740?w=1200&q=80", alt: "Kinfolk Table cookbook cover" },
      { url: "https://images.unsplash.com/photo-1528938102132-4a9276b8e320?w=1200&q=80", alt: "Recipe spread with photography" },
    ],
    price: { min: 3500, max: 4000, currency: "USD" },
    rating: { average: 4.6, count: 2780 },
    buyUrl: "https://kinfolk.com/the-kinfolk-table",
    topFeatures: [
      "85 recipes for small gatherings",
      "Beautifully styled food photography",
      "Stories from hosts around the world",
      "Linen-textured hardcover",
    ],
    description: "A collection of 85 recipes designed for intimate gatherings, paired with Kinfolk's signature minimalist photography. Each chapter features stories from hosts around the world who share their philosophy on bringing people together over food.",
    aspectRatio: 0.90,
    gumis: 38000,
    shares: 3040,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-10",
    title: "Vegetable-Tanned Leather Bookmark",
    brand: "Postalco",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1528938102132-4a9276b8e320?w=600&q=80",
      alt: "Slim leather bookmark tucked into a hardcover novel",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1528938102132-4a9276b8e320?w=1200&q=80", alt: "Postalco leather bookmark detail" },
      { url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=1200&q=80", alt: "Bookmark in use inside an open book" },
    ],
    price: { min: 2200, max: 2800, currency: "USD" },
    rating: { average: 4.5, count: 430 },
    buyUrl: "https://postalco.net/leather-bookmark",
    topFeatures: [
      "Vegetable-tanned Italian leather",
      "Develops rich patina with use",
      "Slim profile won't damage spines",
      "Blind-embossed Postalco logo",
    ],
    description: "A refined leather bookmark crafted from vegetable-tanned Italian hide that ages beautifully over time. The slim profile slips between pages without stressing book spines, making it a thoughtful gift for avid readers.",
    aspectRatio: 0.68,
    gumis: 2800,
    shares: 224,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-11",
    title: "Flip Desk Calendar 2026",
    brand: "Mark + Fold",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&q=80",
      alt: "Minimal flip desk calendar on a clean desk setup",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=1200&q=80", alt: "Desk calendar front view" },
      { url: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1200&q=80", alt: "Desk calendar showing monthly layout" },
    ],
    price: { min: 2800, max: 3500, currency: "USD" },
    rating: { average: 4.4, count: 510 },
    buyUrl: "https://markandfoald.com/flip-desk-calendar",
    topFeatures: [
      "Minimal typographic design",
      "Heavyweight GF Smith paper stock",
      "Brass wire binding and stand",
      "Full year at a glance on reverse",
    ],
    description: "A beautifully restrained desk calendar printed on premium GF Smith paper and bound with brass wire. The clean typographic layout keeps your desk looking sharp while the reverse side provides a full year overview.",
    aspectRatio: 1.10,
    gumis: 3200,
    shares: 256,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-12",
    title: "Portable Watercolor Field Set",
    brand: "Baron Fig",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&q=80",
      alt: "Compact watercolor palette with brush and sketch pad",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1200&q=80", alt: "Watercolor set open with paints" },
      { url: "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=1200&q=80", alt: "Watercolor painting in progress" },
    ],
    price: { min: 3800, max: 4800, currency: "USD" },
    rating: { average: 4.6, count: 740 },
    buyUrl: "https://baronfig.com/watercolor-field-set",
    topFeatures: [
      "18 artist-grade watercolor pans",
      "Collapsible travel water brush included",
      "Magnetic closure tin palette",
      "Integrated mixing area on lid",
      "Pairs with Baron Fig watercolor pads",
    ],
    description: "A compact field watercolor set featuring 18 richly pigmented artist-grade pans in a magnetic closure tin. The lid doubles as a generous mixing palette, making it the perfect companion for plein-air painting and travel sketching.",
    aspectRatio: 1.40,
    gumis: 5800,
    shares: 464,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-13",
    title: "Oblique Calligraphy Pen Set",
    brand: "Ystudio",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=600&q=80",
      alt: "Brass calligraphy pen with nibs and ink bottle on desk",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=1200&q=80", alt: "Ystudio calligraphy pen close-up" },
      { url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1200&q=80", alt: "Calligraphy practice sheet with pen" },
      { url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80", alt: "Complete calligraphy kit contents" },
    ],
    price: { min: 5500, max: 7200, currency: "USD" },
    rating: { average: 4.7, count: 390 },
    buyUrl: "https://ystudiostyle.com/oblique-calligraphy-set",
    topFeatures: [
      "Solid brass oblique pen holder",
      "5 interchangeable steel nibs",
      "Bottle of archival carbon ink",
      "Practice guide booklet included",
    ],
    description: "A precision-machined brass oblique pen holder paired with five interchangeable steel nibs for pointed-pen calligraphy. The set includes a bottle of archival carbon ink and a practice guide to help beginners find their stroke.",
    aspectRatio: 0.72,
    gumis: 2400,
    shares: 192,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-14",
    title: "Rechargeable LED Book Light",
    brand: "Moleskine",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&q=80",
      alt: "Slim LED reading light clipped to an open book",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=1200&q=80", alt: "Moleskine book light in use" },
      { url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80", alt: "Book light folded flat for travel" },
    ],
    price: { min: 2500, max: 3200, currency: "USD" },
    rating: { average: 4.3, count: 1670 },
    buyUrl: "https://moleskine.com/rechargeable-book-light",
    topFeatures: [
      "Ultra-slim rechargeable design",
      "3 brightness levels with warm tone",
      "Flexible gooseneck clip",
      "Up to 20 hours on a single charge",
    ],
    description: "An ultra-slim rechargeable reading light designed to clip seamlessly onto any book or e-reader. Three warm-toned brightness levels and a 20-hour battery life make it ideal for late-night reading sessions.",
    aspectRatio: 0.95,
    gumis: 18000,
    shares: 1440,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-15",
    title: "Padded Canvas Book Sleeve",
    brand: "Field Notes",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&q=80",
      alt: "Waxed canvas book sleeve protecting a hardcover novel",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80", alt: "Book sleeve exterior detail" },
      { url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=1200&q=80", alt: "Book sleeve open showing padded interior" },
    ],
    price: { min: 2200, max: 2800, currency: "USD" },
    rating: { average: 4.5, count: 920 },
    buyUrl: "https://fieldnotesbrand.com/canvas-book-sleeve",
    topFeatures: [
      "Waxed canvas exterior",
      "Padded fleece-lined interior",
      "Fits most hardcovers up to 7x10 inches",
      "YKK brass zipper closure",
    ],
    description: "A rugged waxed canvas book sleeve with a plush fleece-lined interior to protect your favorite reads on the go. The brass zipper and reinforced stitching ensure this sleeve is built to last through years of daily commutes.",
    aspectRatio: 1.05,
    gumis: 4600,
    shares: 368,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-16",
    title: "Blackwing 602 Pencil Set",
    brand: "Blackwing",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&q=80",
      alt: "Set of twelve graphite pencils in a matte black box",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=1200&q=80", alt: "Blackwing 602 pencil set in box" },
      { url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=1200&q=80", alt: "Single Blackwing pencil on paper with shavings" },
    ],
    price: { min: 2800, max: 3500, currency: "USD" },
    rating: { average: 4.8, count: 4200 },
    buyUrl: "https://blackwing602.com/pencil-set",
    topFeatures: [
      "Firm and smooth Japanese graphite core",
      "Iconic flat square ferrule eraser",
      "Genuine incense-cedar barrel",
      "Box of 12 pencils",
      "Preferred by animators, writers, and musicians",
    ],
    description: "The legendary Blackwing 602 pencil, beloved by creators since the 1930s, features a firm yet smooth Japanese graphite core in a genuine incense-cedar barrel. The iconic flat ferrule with replaceable eraser is instantly recognizable.",
    aspectRatio: 0.70,
    gumis: 14500,
    shares: 1160,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-17",
    title: "Letterpress Letter Writing Kit",
    brand: "Crane & Co.",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&q=80",
      alt: "Elegant letter writing set with cream stationery and envelopes",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=1200&q=80", alt: "Crane letter writing kit overview" },
      { url: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=1200&q=80", alt: "Letterpress detail on stationery" },
      { url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=1200&q=80", alt: "Handwritten letter on Crane paper" },
    ],
    price: { min: 4800, max: 6500, currency: "USD" },
    rating: { average: 4.7, count: 680 },
    buyUrl: "https://crane.com/letterpress-writing-kit",
    topFeatures: [
      "100% cotton Lettra paper",
      "Deep impression letterpress printing",
      "20 sheets and 20 lined envelopes",
      "Presented in a keepsake box",
    ],
    description: "Exquisite letter writing stationery featuring deep-impression letterpress printing on Crane's signature 100% cotton Lettra paper. The kit includes twenty sheets and matching lined envelopes, all presented in an elegant keepsake box.",
    aspectRatio: 1.30,
    gumis: 5600,
    shares: 448,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-18",
    title: "Techo Planner Weeks 2026",
    brand: "Hobonichi",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&q=80",
      alt: "Hobonichi weekly planner with colorful fabric cover",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=1200&q=80", alt: "Hobonichi planner cover close-up" },
      { url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=1200&q=80", alt: "Hobonichi weekly spread layout" },
    ],
    price: { min: 3200, max: 4500, currency: "USD" },
    rating: { average: 4.8, count: 3650 },
    buyUrl: "https://hobonichi.net/techo-weeks-2026",
    topFeatures: [
      "Tomoe River paper — ultra-thin, fountain pen friendly",
      "Weekly left, memo right layout",
      "Wallet-sized slim profile",
      "180-degree flat opening",
      "Yearly and monthly indexes included",
    ],
    description: "The cult-favorite Hobonichi Techo Weeks fits in your back pocket yet provides a full year of weekly planning on iconic Tomoe River paper. The left-side weekly layout paired with a right-side memo page strikes the perfect balance between structure and freedom.",
    aspectRatio: 0.78,
    gumis: 35000,
    shares: 2800,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-19",
    title: "Stone Memo Block",
    brand: "Postalco",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=600&q=80",
      alt: "Cuboid memo pad on a desk next to a pen holder",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=1200&q=80", alt: "Postalco memo block close-up" },
      { url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=1200&q=80", alt: "Memo block with handwritten notes" },
    ],
    price: { min: 1400, max: 1800, currency: "USD" },
    rating: { average: 4.3, count: 350 },
    buyUrl: "https://postalco.net/stone-memo-block",
    topFeatures: [
      "480 sheets of smooth unlined paper",
      "Stone paper — water-resistant and durable",
      "Compact cube form factor",
      "Subtle debossed branding",
    ],
    description: "A dense cube of 480 stone paper sheets that sits elegantly on any desk. The water-resistant, ultra-smooth paper works beautifully with any pen and the compact form factor makes it an endlessly useful desk companion.",
    aspectRatio: 1.00,
    gumis: 2100,
    shares: 168,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-20",
    title: "Transparent Sticky Notes Set",
    brand: "Leuchtturm1917",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=600&q=80",
      alt: "Transparent sticky notes in multiple colors on a notebook page",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1553729784-e91953dec042?w=1200&q=80", alt: "Leuchtturm sticky notes overview" },
      { url: "https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=1200&q=80", alt: "Transparent notes used for annotating a book" },
    ],
    price: { min: 1200, max: 1600, currency: "USD" },
    rating: { average: 4.4, count: 1280 },
    buyUrl: "https://leuchtturm1917.com/transparent-sticky-notes",
    topFeatures: [
      "See-through design for annotating text",
      "6 coordinated pastel colors",
      "3 sizes for different uses",
      "Repositionable adhesive won't damage pages",
    ],
    description: "Transparent sticky notes that let you annotate directly over text without obscuring the words beneath. The set includes six pastel colors in three sizes, with a gentle adhesive that repositions cleanly on any paper surface.",
    aspectRatio: 1.55,
    gumis: 16000,
    shares: 1280,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-21",
    title: "Obsidian Glass Paperweight",
    brand: "Ystudio",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=600&q=80",
      alt: "Polished obsidian glass paperweight on a stack of papers",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=1200&q=80", alt: "Ystudio paperweight close-up" },
      { url: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=1200&q=80", alt: "Paperweight on a styled desk" },
    ],
    price: { min: 4500, max: 5800, currency: "USD" },
    rating: { average: 4.6, count: 280 },
    buyUrl: "https://ystudiostyle.com/obsidian-paperweight",
    topFeatures: [
      "Hand-polished obsidian volcanic glass",
      "Satisfying heft at 320 grams",
      "Organic asymmetric form",
      "Each piece is naturally unique",
    ],
    description: "A hand-polished obsidian paperweight that doubles as a sculptural desk object. Each piece is cut from natural volcanic glass with organic asymmetry, meaning no two are alike. The satisfying weight keeps papers firmly in place.",
    aspectRatio: 0.88,
    gumis: 2600,
    shares: 208,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-22",
    title: "Softcover Dot Grid Notebook",
    brand: "Leuchtturm1917",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=600&q=80",
      alt: "Softcover dot grid notebook in muted sage green",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=1200&q=80", alt: "Leuchtturm softcover notebook cover" },
      { url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=1200&q=80", alt: "Dot grid interior pages" },
      { url: "https://images.unsplash.com/photo-1529473814998-077b4fec6770?w=1200&q=80", alt: "Notebook open flat on a desk" },
    ],
    price: { min: 1995, max: 2495, currency: "USD" },
    rating: { average: 4.7, count: 4850 },
    buyUrl: "https://leuchtturm1917.com/softcover-dot-grid",
    topFeatures: [
      "123 numbered dot grid pages",
      "80gsm acid-free paper",
      "Thread-bound for flat opening",
      "Table of contents and page markers",
      "Available in 20+ colors",
    ],
    description: "The go-to notebook for bullet journaling, sketching, and note-taking, featuring 123 numbered dot grid pages on smooth 80gsm acid-free paper. The softcover flexes easily in hand while the thread binding ensures it opens completely flat.",
    aspectRatio: 0.80,
    gumis: 31000,
    shares: 2480,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-23",
    title: "Expeditionary Memo Books 3-Pack",
    brand: "Field Notes",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80",
      alt: "Three pocket-sized memo books with kraft covers",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=1200&q=80", alt: "Field Notes memo books fanned out" },
      { url: "https://images.unsplash.com/photo-1529473814998-077b4fec6770?w=1200&q=80", alt: "Memo book open showing graph paper" },
    ],
    price: { min: 1295, max: 1495, currency: "USD" },
    rating: { average: 4.6, count: 3920 },
    buyUrl: "https://fieldnotesbrand.com/expeditionary",
    topFeatures: [
      "Water-resistant Yupo synthetic paper",
      "Tearproof and weatherproof pages",
      "3.5 x 5.5 inch pocket size",
      "48 pages per book, graph ruled",
      "Pack of 3 with saddle-stitch binding",
    ],
    description: "Field Notes' most durable memo book, printed on waterproof Yupo synthetic paper that stands up to rain, sweat, and spills. The pocket-sized format and graph-ruled pages make these indispensable for field work, hiking, or any outdoor adventure.",
    aspectRatio: 0.67,
    gumis: 11000,
    shares: 880,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-24",
    title: "Garden Party Social Stationery",
    brand: "Rifle Paper Co.",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1529473814998-077b4fec6770?w=600&q=80",
      alt: "Floral stationery set with illustrated envelopes and cards",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1529473814998-077b4fec6770?w=1200&q=80", alt: "Rifle Paper Co. stationery set overview" },
      { url: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=1200&q=80", alt: "Illustrated floral card close-up" },
      { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1200&q=80", alt: "Stationery set with pen and flowers" },
    ],
    price: { min: 2400, max: 3200, currency: "USD" },
    rating: { average: 4.5, count: 1540 },
    buyUrl: "https://riflepaperco.com/garden-party-stationery",
    topFeatures: [
      "12 flat cards with hand-painted floral motifs",
      "12 matching lined envelopes",
      "Printed on heavyweight cotton paper",
      "Gold foil accents throughout",
    ],
    description: "A charming social stationery set featuring Rifle Paper Co.'s hand-painted garden illustrations with gold foil accents. Twelve flat cards and matching lined envelopes are printed on luxurious heavyweight cotton paper for correspondence that feels truly special.",
    aspectRatio: 1.20,
    gumis: 7200,
    shares: 576,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "books-25",
    title: "Palomino Luxury Pencil Set",
    brand: "Palomino",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=600&q=80",
      alt: "Premium graphite pencils in a cedar wood box",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=1200&q=80", alt: "Palomino pencils in cedar box" },
      { url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=1200&q=80", alt: "Pencil graphite grade comparison" },
    ],
    price: { min: 2400, max: 3200, currency: "USD" },
    rating: { average: 4.7, count: 1870 },
    buyUrl: "https://palominopencils.com/luxury-set",
    topFeatures: [
      "12 pencils in grades HB through 6B",
      "California incense-cedar barrels",
      "Ultra-smooth Japanese graphite cores",
      "Handcrafted cedar presentation box",
      "Includes brass long-point sharpener",
    ],
    description: "A curated set of twelve premium graphite pencils spanning HB through 6B, housed in a handcrafted cedar presentation box. Each pencil features California incense-cedar and a silky Japanese graphite core that lays down smooth, rich lines.",
    aspectRatio: 1.48,
    gumis: 9500,
    shares: 760,
    gumiedByFriends: getRandomGumiFriends(),
  },
];
