import { Product } from "@/types";
import { getRandomGumiFriends } from "../mock-users";


export const HOME_PRODUCTS: Product[] = [
  // ─── 1. Boucle Sofa ──────────────────────────────────
  {
    id: "home-1",
    title: "Sven Boucle Sofa",
    brand: "Article",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80",
      alt: "Cream boucle sofa in living room",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", alt: "Cream boucle sofa in living room" },
      { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80", alt: "Sofa detail shot" },
    ],
    price: { min: 179900, max: 219900, currency: "USD" },
    rating: { average: 4.7, count: 1243 },
    buyUrl: "https://article.com",
    topFeatures: ["Boucle Upholstery", "Solid Oak Legs", "86\" Width", "Removable Cushion Covers"],
    description: "A statement sofa wrapped in plush ivory boucle fabric. The clean mid-century silhouette pairs effortlessly with any living room style while the deep seat invites you to sink in and stay awhile.",
    aspectRatio: 1.45,
    gumis: 14200,
    shares: 1560,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 2. Travertine Coffee Table ───────────────────────
  {
    id: "home-2",
    title: "Travertine Round Coffee Table",
    brand: "CB2",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80",
      alt: "Round travertine coffee table",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=80", alt: "Round travertine coffee table" },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80", alt: "Coffee table in styled living room" },
    ],
    price: { min: 89900, max: 119900, currency: "USD" },
    rating: { average: 4.8, count: 567 },
    buyUrl: "https://cb2.com",
    topFeatures: ["Natural Travertine", "36\" Diameter", "Pedestal Base", "Each Piece Unique"],
    description: "Carved from a single block of Italian travertine, this sculptural coffee table brings organic warmth to any space. Natural veining ensures no two tables are alike.",
    aspectRatio: 0.95,
    gumis: 18700,
    shares: 2050,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 3. Ceramic Table Lamp ────────────────────────────
  {
    id: "home-3",
    title: "Ceramic Table Lamp",
    brand: "Rejuvenation",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
      alt: "Ceramic table lamp with linen shade",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", alt: "Ceramic table lamp with linen shade" },
      { url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1200&q=80", alt: "Lamp detail" },
    ],
    price: { min: 24900, max: 29900, currency: "USD" },
    rating: { average: 4.6, count: 312 },
    buyUrl: "https://rejuvenation.com",
    topFeatures: ["Hand-Glazed Ceramic", "Linen Drum Shade", "3-Way Switch", "UL Listed"],
    description: "A hand-glazed ceramic base gives this lamp an artisan feel that elevates any bedside or console. The natural linen shade casts a warm, inviting glow throughout the room.",
    aspectRatio: 1.35,
    gumis: 9800,
    shares: 1070,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 4. Arch Floor Mirror ─────────────────────────────
  {
    id: "home-4",
    title: "Arch Floor Mirror",
    brand: "West Elm",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=600&q=80",
      alt: "Arched floor mirror leaning against wall",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", alt: "Arched floor mirror leaning against wall" },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80", alt: "Mirror in styled bedroom" },
    ],
    price: { min: 39900, max: 59900, currency: "USD" },
    rating: { average: 4.8, count: 891 },
    buyUrl: "https://westelm.com",
    topFeatures: ["Brass-Finished Frame", "70\" x 30\"", "Wall Mount or Lean", "Shatter-Resistant"],
    description: "This oversized arch mirror instantly opens up any room and adds a touch of timeless elegance. The slim brass frame keeps it feeling light and modern, whether mounted or casually leaned against a wall.",
    aspectRatio: 0.65,
    gumis: 22400,
    shares: 2460,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 5. Sculptural Bookend Set ────────────────────────
  {
    id: "home-5",
    title: "Abstract Sculptural Bookends",
    brand: "CB2",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",
      alt: "Sculptural stone bookends on shelf",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=1200&q=80", alt: "Sculptural stone bookends on shelf" },
      { url: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=1200&q=80", alt: "Bookends styled on bookshelf" },
    ],
    price: { min: 5900, max: 7900, currency: "USD" },
    rating: { average: 4.5, count: 189 },
    buyUrl: "https://cb2.com",
    topFeatures: ["Cast Resin", "Set of 2", "Non-Scratch Base", "Weighted Design"],
    description: "These sculptural bookends double as standalone art pieces. The abstract organic shapes add visual interest to any shelf while keeping your favorite reads firmly in place.",
    aspectRatio: 1.0,
    gumis: 11300,
    shares: 1240,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 6. Marble Decorative Tray ────────────────────────
  {
    id: "home-6",
    title: "Marble Vanity Tray",
    brand: "McGee & Co.",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=600&q=80",
      alt: "White marble tray with gold handles",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80", alt: "White marble tray with gold handles" },
      { url: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=1200&q=80", alt: "Tray styled with candles" },
    ],
    price: { min: 8900, max: 12900, currency: "USD" },
    rating: { average: 4.7, count: 234 },
    buyUrl: "https://mcgeeandco.com",
    topFeatures: ["Calacatta Marble", "Brass Handles", "12\" x 8\"", "Felt-Padded Base"],
    description: "Elevate your vanity, coffee table, or bathroom counter with this polished Calacatta marble tray. Brass handles add a refined touch, making it as functional as it is beautiful.",
    aspectRatio: 1.3,
    gumis: 5600,
    shares: 615,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 7. Terracotta Planter ────────────────────────────
  {
    id: "home-7",
    title: "Ribbed Terracotta Planter",
    brand: "The Citizenry",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
      alt: "Terracotta planter with plant",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80", alt: "Terracotta planter with plant" },
      { url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=1200&q=80", alt: "Planter grouping" },
    ],
    price: { min: 6800, max: 12800, currency: "USD" },
    rating: { average: 4.6, count: 456 },
    buyUrl: "https://the-citizenry.com",
    topFeatures: ["Handmade in Oaxaca", "Drainage Hole", "Weather Resistant", "Indoor/Outdoor"],
    description: "Hand-shaped by artisans in Oaxaca, this ribbed terracotta planter brings earthy warmth to your plant collection. Each piece bears subtle variations that make it one of a kind.",
    aspectRatio: 0.85,
    gumis: 4200,
    shares: 460,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 8. Linen Curtain Panels ──────────────────────────
  {
    id: "home-8",
    title: "Washed Linen Curtain Panel",
    brand: "Serena & Lily",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=80",
      alt: "Sheer linen curtains in sunlit room",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Sheer linen curtains in sunlit room" },
      { url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80", alt: "Curtain texture closeup" },
    ],
    price: { min: 12800, max: 19800, currency: "USD" },
    rating: { average: 4.5, count: 678 },
    buyUrl: "https://serenaandlily.com",
    topFeatures: ["100% Belgian Linen", "Rod Pocket or Clip Ring", "50\" x 96\"", "OEKO-TEX Certified"],
    description: "These washed Belgian linen panels filter light beautifully while adding effortless texture to any window. The pre-washed finish gives them a soft, lived-in drape from day one.",
    aspectRatio: 0.70,
    gumis: 19600,
    shares: 2150,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 9. Woven Seagrass Basket ─────────────────────────
  {
    id: "home-9",
    title: "Seagrass Storage Basket",
    brand: "The Citizenry",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=600&q=80",
      alt: "Woven seagrass basket with blankets",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80", alt: "Woven seagrass basket with blankets" },
      { url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=80", alt: "Basket in styled room" },
    ],
    price: { min: 8500, max: 14500, currency: "USD" },
    rating: { average: 4.7, count: 523 },
    buyUrl: "https://the-citizenry.com",
    topFeatures: ["Hand-Woven Seagrass", "Leather Handles", "Collapsible", "Fair Trade Certified"],
    description: "An endlessly versatile storage basket woven from sustainably harvested seagrass. Use it for throw blankets, magazines, toys, or laundry — it looks stunning wherever you put it.",
    aspectRatio: 1.05,
    gumis: 3800,
    shares: 415,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 10. Velvet Throw Pillow ──────────────────────────
  {
    id: "home-10",
    title: "Velvet Lumbar Pillow",
    brand: "Lulu & Georgia",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80",
      alt: "Velvet lumbar pillow on sofa",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Velvet lumbar pillow on sofa" },
      { url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=1200&q=80", alt: "Pillow arrangement" },
    ],
    price: { min: 6800, max: 8900, currency: "USD" },
    rating: { average: 4.6, count: 345 },
    buyUrl: "https://luluandgeorgia.com",
    topFeatures: ["Cotton Velvet", "Down-Feather Insert", "12\" x 20\"", "Hidden Zipper"],
    description: "Rich cotton velvet in a moody sage tone makes this lumbar pillow the perfect finishing touch. The plump down-feather insert keeps it looking full and inviting for years.",
    aspectRatio: 1.40,
    gumis: 12800,
    shares: 1400,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 11. Wool Area Rug ────────────────────────────────
  {
    id: "home-11",
    title: "Handwoven Wool Area Rug",
    brand: "Lulu & Georgia",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80",
      alt: "Textured wool area rug in neutral tones",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1602928321679-560bb453f190?w=1200&q=80", alt: "Textured wool area rug in neutral tones" },
      { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80", alt: "Rug in living room setting" },
    ],
    price: { min: 89900, max: 249900, currency: "USD" },
    rating: { average: 4.8, count: 712 },
    buyUrl: "https://luluandgeorgia.com",
    topFeatures: ["100% New Zealand Wool", "Handwoven", "5' x 8' to 9' x 12'", "GoodWeave Certified"],
    description: "This handwoven area rug grounds any room with its rich texture and creamy neutral palette. Crafted from New Zealand wool, it feels incredibly soft underfoot and only gets better with age.",
    aspectRatio: 1.50,
    gumis: 16500,
    shares: 1810,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 12. Floating Shelf ───────────────────────────────
  {
    id: "home-12",
    title: "Oak Floating Shelf",
    brand: "Schoolhouse",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=600&q=80",
      alt: "Floating oak shelf with decor objects",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", alt: "Floating oak shelf with decor objects" },
      { url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=1200&q=80", alt: "Shelf installation" },
    ],
    price: { min: 14900, max: 24900, currency: "USD" },
    rating: { average: 4.7, count: 489 },
    buyUrl: "https://schoolhouse.com",
    topFeatures: ["White Oak", "Hidden Bracket", "24\" / 36\" / 48\"", "Made in Portland"],
    description: "A clean, minimal floating shelf in warm white oak that lets your objects shine. The hidden bracket system creates a seamless look and supports up to 30 pounds.",
    aspectRatio: 1.55,
    gumis: 7300,
    shares: 800,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 13. Ceramic Vase ─────────────────────────────────
  {
    id: "home-13",
    title: "Stoneware Bud Vase",
    brand: "East Fork",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80",
      alt: "Handmade ceramic bud vase",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Handmade ceramic bud vase" },
      { url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=1200&q=80", alt: "Vase with dried flowers" },
      { url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=1200&q=80", alt: "Vase collection" },
    ],
    price: { min: 4800, max: 6800, currency: "USD" },
    rating: { average: 4.9, count: 867 },
    buyUrl: "https://eastfork.com",
    topFeatures: ["Handmade in Asheville", "Lead-Free Glaze", "Dishwasher Safe", "Watertight"],
    description: "A beautifully proportioned bud vase hand-thrown in East Fork's Asheville studio. The reactive glaze creates gorgeous color variations that make each piece truly unique.",
    aspectRatio: 0.75,
    gumis: 6100,
    shares: 670,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 14. Scented Candle ───────────────────────────────
  {
    id: "home-14",
    title: "Soy Wax Candle — Fireside",
    brand: "Schoolhouse",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600&q=80",
      alt: "Minimal scented candle in amber glass",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Minimal scented candle in amber glass" },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", alt: "Candle lit on shelf" },
    ],
    price: { min: 3400, max: 4200, currency: "USD" },
    rating: { average: 4.7, count: 1456 },
    buyUrl: "https://schoolhouse.com",
    topFeatures: ["100% Soy Wax", "Cotton Wick", "60-Hour Burn", "Made in USA"],
    description: "Notes of cedar, clove, and warm amber fill your space with the cozy scent of a crackling fire. Poured from clean-burning soy wax in a reusable amber glass vessel.",
    aspectRatio: 0.80,
    gumis: 4800,
    shares: 525,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 15. Duvet Cover Set ──────────────────────────────
  {
    id: "home-15",
    title: "Stonewashed Linen Duvet Set",
    brand: "Serena & Lily",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
      alt: "Linen duvet on made bed",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80", alt: "Linen duvet on made bed" },
      { url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=80", alt: "Bedroom styled view" },
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80", alt: "Bedding texture detail" },
    ],
    price: { min: 24800, max: 34800, currency: "USD" },
    rating: { average: 4.8, count: 934 },
    buyUrl: "https://serenaandlily.com",
    topFeatures: ["100% French Linen", "Includes 2 Shams", "Button Closure", "Pre-Washed"],
    description: "Sleep enveloped in the luxurious softness of pre-washed French linen. This duvet set includes two matching shams and only gets softer with every wash — a bedroom essential you will reach for season after season.",
    aspectRatio: 1.20,
    gumis: 21300,
    shares: 2340,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 16. Side Table ───────────────────────────────────
  {
    id: "home-16",
    title: "Walnut Side Table",
    brand: "Article",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
      alt: "Walnut side table next to sofa",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=1200&q=80", alt: "Walnut side table next to sofa" },
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", alt: "Side table in room setting" },
    ],
    price: { min: 24900, max: 34900, currency: "USD" },
    rating: { average: 4.6, count: 678 },
    buyUrl: "https://article.com",
    topFeatures: ["Solid Walnut", "Shelf Storage", "20\" Height", "Tapered Legs"],
    description: "A mid-century inspired side table in rich walnut that works as hard as it looks. The lower shelf provides extra storage for books and remotes without adding visual bulk.",
    aspectRatio: 0.90,
    gumis: 13700,
    shares: 1500,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 17. Pendant Light ────────────────────────────────
  {
    id: "home-17",
    title: "Rattan Pendant Light",
    brand: "Serena & Lily",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&q=80",
      alt: "Woven rattan pendant lamp",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=80", alt: "Woven rattan pendant lamp" },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", alt: "Pendant lamp casting shadows" },
    ],
    price: { min: 34800, max: 49800, currency: "USD" },
    rating: { average: 4.7, count: 234 },
    buyUrl: "https://serenaandlily.com",
    topFeatures: ["Hand-Woven Rattan", "18\" Diameter", "Adjustable Drop", "Dimmable Compatible"],
    description: "This hand-woven rattan pendant casts beautiful dappled shadows and brings instant warmth to kitchens, dining rooms, and entryways. The natural material adds organic texture overhead.",
    aspectRatio: 0.75,
    gumis: 17200,
    shares: 1890,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 18. Wall Hooks ───────────────────────────────────
  {
    id: "home-18",
    title: "Brass Wall Hook Set",
    brand: "Schoolhouse",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80",
      alt: "Brass wall hooks with items hanging",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Brass wall hooks with items hanging" },
      { url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=1200&q=80", alt: "Hook detail shot" },
    ],
    price: { min: 4900, max: 7900, currency: "USD" },
    rating: { average: 4.5, count: 567 },
    buyUrl: "https://schoolhouse.com",
    topFeatures: ["Solid Brass", "Set of 3", "Holds 10 lbs Each", "Made in Portland"],
    description: "Simple, solid, and beautifully made. These cast brass hooks are built to last a lifetime and develop a gorgeous patina over time. Perfect for entryways, bathrooms, and bedrooms.",
    aspectRatio: 1.10,
    gumis: 5900,
    shares: 645,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 19. Desk Lamp ────────────────────────────────────
  {
    id: "home-19",
    title: "Task Desk Lamp",
    brand: "Hay",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
      alt: "Minimal desk lamp on workspace",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80", alt: "Minimal desk lamp on workspace" },
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80", alt: "Lamp in home office" },
    ],
    price: { min: 11900, max: 15900, currency: "USD" },
    rating: { average: 4.6, count: 423 },
    buyUrl: "https://hay.dk",
    topFeatures: ["Die-Cast Aluminum", "Adjustable Arm", "LED Bulb Included", "Color: Soft Black"],
    description: "A Danish-designed task lamp that nails the balance between form and function. The fully adjustable arm directs light exactly where you need it, while the streamlined profile keeps your desk looking clean.",
    aspectRatio: 1.15,
    gumis: 38400,
    shares: 4220,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 20. Storage Ottoman ──────────────────────────────
  {
    id: "home-20",
    title: "Boucle Storage Ottoman",
    brand: "West Elm",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80",
      alt: "Round boucle ottoman with storage",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80", alt: "Round boucle ottoman with storage" },
      { url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80", alt: "Ottoman in living room" },
    ],
    price: { min: 34900, max: 44900, currency: "USD" },
    rating: { average: 4.5, count: 345 },
    buyUrl: "https://westelm.com",
    topFeatures: ["Boucle Fabric", "Hidden Storage", "Solid Wood Legs", "25\" Diameter"],
    description: "This plush boucle ottoman works triple duty as a footrest, extra seat, and clever storage solution. Lift the cushion top to reveal a generous interior that stashes blankets, pillows, or toys.",
    aspectRatio: 1.00,
    gumis: 15900,
    shares: 1745,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 21. Woven Throw Blanket ──────────────────────────
  {
    id: "home-21",
    title: "Alpaca Throw Blanket",
    brand: "The Citizenry",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=80",
      alt: "Alpaca throw blanket draped on chair",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&q=80", alt: "Alpaca throw blanket draped on chair" },
      { url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=1200&q=80", alt: "Throw blanket texture" },
    ],
    price: { min: 14900, max: 19900, currency: "USD" },
    rating: { average: 4.8, count: 612 },
    buyUrl: "https://the-citizenry.com",
    topFeatures: ["Baby Alpaca Wool", "60\" x 80\"", "Hand-Loomed in Peru", "Hypoallergenic"],
    description: "Woven from baby alpaca wool by artisans in the Peruvian highlands, this throw is impossibly soft and lightweight. The subtle stripe pattern adds just enough visual interest without overwhelming your sofa.",
    aspectRatio: 0.80,
    gumis: 7600,
    shares: 835,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 22. Abstract Wall Art ────────────────────────────
  {
    id: "home-22",
    title: "Abstract Canvas Print",
    brand: "Anthropologie Home",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80",
      alt: "Abstract art print on wall",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=1200&q=80", alt: "Abstract art print on wall" },
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80", alt: "Art styled in gallery wall" },
    ],
    price: { min: 14800, max: 39800, currency: "USD" },
    rating: { average: 4.6, count: 189 },
    buyUrl: "https://anthropologie.com",
    topFeatures: ["Giclée on Canvas", "Gallery Wrapped", "24\" x 36\" / 36\" x 48\"", "Ready to Hang"],
    description: "A museum-quality giclée print on gallery-wrapped canvas that brings movement and color to any blank wall. The abstract composition works in both modern and traditional spaces.",
    aspectRatio: 0.70,
    gumis: 10400,
    shares: 1140,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 23. Linen Napkin Set ─────────────────────────────
  {
    id: "home-23",
    title: "Linen Dinner Napkins",
    brand: "Hay",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
      alt: "Folded linen napkins on table",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80", alt: "Folded linen napkins on table" },
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Napkins in table setting" },
    ],
    price: { min: 3200, max: 4500, currency: "USD" },
    rating: { average: 4.5, count: 234 },
    buyUrl: "https://hay.dk",
    topFeatures: ["Stonewashed Linen", "Set of 4", "20\" x 20\"", "OEKO-TEX Certified"],
    description: "Elevate every meal with these stonewashed linen napkins in muted earth tones. They soften beautifully with each wash and add effortless European elegance to your table.",
    aspectRatio: 1.0,
    gumis: 29700,
    shares: 3260,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 24. Ceramic Candle Holder ────────────────────────
  {
    id: "home-24",
    title: "Stoneware Taper Candle Holder",
    brand: "East Fork",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80",
      alt: "Ceramic candle holder with taper candle",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80", alt: "Ceramic candle holder with taper candle" },
      { url: "https://images.unsplash.com/photo-1602928321679-560bb453f190?w=1200&q=80", alt: "Candle holders grouped" },
    ],
    price: { min: 3600, max: 4800, currency: "USD" },
    rating: { average: 4.7, count: 345 },
    buyUrl: "https://eastfork.com",
    topFeatures: ["Hand-Thrown Stoneware", "Fits Standard Tapers", "Weighted Base", "Reactive Glaze"],
    description: "A perfectly proportioned taper holder hand-thrown in East Fork's signature reactive glaze. The weighted base keeps candles stable, and the organic shape adds a handmade touch to any table.",
    aspectRatio: 0.70,
    gumis: 5200,
    shares: 570,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 25. Jute Area Rug ───────────────────────────────
  {
    id: "home-25",
    title: "Braided Jute Rug",
    brand: "Restoration Hardware",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80",
      alt: "Natural jute rug in dining room",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", alt: "Natural jute rug in dining room" },
      { url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", alt: "Rug texture closeup" },
    ],
    price: { min: 59900, max: 179900, currency: "USD" },
    rating: { average: 4.5, count: 456 },
    buyUrl: "https://rh.com",
    topFeatures: ["100% Natural Jute", "Reversible", "6' x 9' to 10' x 14'", "Low Profile"],
    description: "A classic braided jute rug that layers beautifully and works in virtually every room. The natural fiber construction is durable, sustainable, and brings instant coastal warmth to your floors.",
    aspectRatio: 1.40,
    gumis: 24600,
    shares: 2700,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 26. Vanity Mirror ────────────────────────────────
  {
    id: "home-26",
    title: "Round Vanity Mirror",
    brand: "Rejuvenation",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=600&q=80",
      alt: "Round mirror above bathroom vanity",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=1200&q=80", alt: "Round mirror above bathroom vanity" },
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Mirror in styled space" },
    ],
    price: { min: 29900, max: 44900, currency: "USD" },
    rating: { average: 4.7, count: 312 },
    buyUrl: "https://rejuvenation.com",
    topFeatures: ["Oil-Rubbed Bronze Frame", "30\" Diameter", "Beveled Edge", "Wall Mount Hardware Included"],
    description: "A beautifully proportioned round mirror that softens the lines of any room. The slim oil-rubbed bronze frame adds subtle contrast, and the beveled edge catches light for extra depth.",
    aspectRatio: 0.90,
    gumis: 8500,
    shares: 930,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 27. Cotton Bedsheet Set ──────────────────────────
  {
    id: "home-27",
    title: "Percale Sheet Set",
    brand: "Crate & Barrel",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
      alt: "Crisp white sheets on bed",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=1200&q=80", alt: "Crisp white sheets on bed" },
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Sheet texture detail" },
    ],
    price: { min: 14900, max: 22900, currency: "USD" },
    rating: { average: 4.6, count: 1123 },
    buyUrl: "https://crateandbarrel.com",
    topFeatures: ["400-Thread-Count Percale", "Long-Staple Cotton", "Deep Pocket Fitted", "OEKO-TEX Certified"],
    description: "Hotel-quality percale sheets with that satisfying crisp hand-feel. Long-staple cotton ensures durability and softness that improves with every wash. The perfect foundation for a well-made bed.",
    aspectRatio: 1.30,
    gumis: 11900,
    shares: 1305,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 28. Modular Shelving ─────────────────────────────
  {
    id: "home-28",
    title: "Modular Wall Shelving System",
    brand: "Muji",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=600&q=80",
      alt: "Minimalist modular shelving unit",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80", alt: "Minimalist modular shelving unit" },
      { url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80", alt: "Shelving with styled objects" },
    ],
    price: { min: 24900, max: 44900, currency: "USD" },
    rating: { average: 4.8, count: 789 },
    buyUrl: "https://muji.com",
    topFeatures: ["Pine Wood", "Customizable Configuration", "Wall-Mounted", "Tool-Free Assembly"],
    description: "Muji's iconic modular shelving adapts to any space and any need. The clean pine construction disappears into your wall while giving you complete freedom to rearrange shelves, drawers, and cabinets.",
    aspectRatio: 0.75,
    gumis: 42300,
    shares: 4645,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 29. Stoneware Dinner Set ─────────────────────────
  {
    id: "home-29",
    title: "Stoneware Dinnerware Set",
    brand: "East Fork",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80",
      alt: "Handmade stoneware dinnerware stack",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80", alt: "Handmade stoneware dinnerware stack" },
      { url: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=1200&q=80", alt: "Place setting" },
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", alt: "Dinnerware collection" },
    ],
    price: { min: 18500, max: 29500, currency: "USD" },
    rating: { average: 4.9, count: 1567 },
    buyUrl: "https://eastfork.com",
    topFeatures: ["16-Piece Set", "Handmade in NC", "Microwave & Dishwasher Safe", "Lead-Free Glaze"],
    description: "A complete dinnerware set for four in East Fork's beloved reactive glaze. Each piece is hand-thrown by their team of potters in Asheville, resulting in slight variations that make every meal feel special.",
    aspectRatio: 1.05,
    gumis: 6800,
    shares: 745,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 30. Accent Chair ─────────────────────────────────
  {
    id: "home-30",
    title: "Upholstered Accent Chair",
    brand: "Article",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
      alt: "Mid-century accent chair in olive",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1200&q=80", alt: "Mid-century accent chair in olive" },
      { url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=80", alt: "Chair in living room" },
    ],
    price: { min: 79900, max: 119900, currency: "USD" },
    rating: { average: 4.7, count: 534 },
    buyUrl: "https://article.com",
    topFeatures: ["Performance Fabric", "Solid Oak Frame", "High-Density Foam", "30\" Wide"],
    description: "A sculptural accent chair that commands attention without overwhelming a room. The performance fabric resists stains while the high-density foam seat keeps its shape through years of everyday use.",
    aspectRatio: 0.85,
    gumis: 16800,
    shares: 1845,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 31. Diffuser ─────────────────────────────────────
  {
    id: "home-31",
    title: "Reed Diffuser — Eucalyptus",
    brand: "Muji",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1602928321679-560bb453f190?w=600&q=80",
      alt: "Minimal reed diffuser on shelf",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80", alt: "Minimal reed diffuser on shelf" },
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Diffuser in bathroom" },
    ],
    price: { min: 2400, max: 3200, currency: "USD" },
    rating: { average: 4.4, count: 567 },
    buyUrl: "https://muji.com",
    topFeatures: ["Essential Oil Blend", "Glass Vessel", "6 Reeds Included", "Lasts 3 Months"],
    description: "A clean, flame-free way to scent any room with refreshing eucalyptus. The frosted glass vessel looks elegant on any surface, and the natural rattan reeds disperse fragrance continuously.",
    aspectRatio: 0.68,
    gumis: 31200,
    shares: 3425,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 32. Dining Table ─────────────────────────────────
  {
    id: "home-32",
    title: "Extendable Dining Table",
    brand: "West Elm",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80",
      alt: "Wood dining table in open kitchen",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=1200&q=80", alt: "Wood dining table in open kitchen" },
      { url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80", alt: "Table with chairs" },
    ],
    price: { min: 129900, max: 179900, currency: "USD" },
    rating: { average: 4.6, count: 312 },
    buyUrl: "https://westelm.com",
    topFeatures: ["Solid Acacia Wood", "Extends to 86\"", "Seats 6-8", "Protective Lacquer Finish"],
    description: "A warm acacia wood dining table that grows with your gatherings. The built-in leaf extends the surface to seat eight comfortably, then tucks away for everyday use.",
    aspectRatio: 1.45,
    gumis: 20100,
    shares: 2205,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 33. Wall Planter ─────────────────────────────────
  {
    id: "home-33",
    title: "Ceramic Wall Planter",
    brand: "Anthropologie Home",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
      alt: "Ceramic wall planter with trailing plant",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=1200&q=80", alt: "Ceramic wall planter with trailing plant" },
      { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80", alt: "Wall planter detail" },
    ],
    price: { min: 3800, max: 5800, currency: "USD" },
    rating: { average: 4.5, count: 234 },
    buyUrl: "https://anthropologie.com",
    topFeatures: ["Glazed Stoneware", "Built-In Drainage", "Mounting Hardware Included", "6\" Opening"],
    description: "A charming wall-mounted planter perfect for trailing pothos or ferns. The speckled glaze adds artisan character to any wall, turning your plants into living art.",
    aspectRatio: 0.85,
    gumis: 9300,
    shares: 1020,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 34. Throw Pillow Cover ───────────────────────────
  {
    id: "home-34",
    title: "Textured Linen Pillow Cover",
    brand: "McGee & Co.",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80",
      alt: "Textured linen pillow on bed",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=1200&q=80", alt: "Textured linen pillow on bed" },
      { url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&q=80", alt: "Pillow arrangement" },
    ],
    price: { min: 4800, max: 6800, currency: "USD" },
    rating: { average: 4.6, count: 456 },
    buyUrl: "https://mcgeeandco.com",
    topFeatures: ["100% Linen", "22\" x 22\"", "Hidden Zipper", "Insert Sold Separately"],
    description: "A beautifully textured linen pillow cover in a soft oatmeal tone that pairs with everything. The slubby weave adds visual depth and dimension to your sofa or bed.",
    aspectRatio: 1.0,
    gumis: 4500,
    shares: 495,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 35. Media Console ────────────────────────────────
  {
    id: "home-35",
    title: "Oak Media Console",
    brand: "Crate & Barrel",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80",
      alt: "Modern oak media console",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&q=80", alt: "Modern oak media console" },
      { url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=1200&q=80", alt: "Console in living room" },
    ],
    price: { min: 149900, max: 199900, currency: "USD" },
    rating: { average: 4.7, count: 278 },
    buyUrl: "https://crateandbarrel.com",
    topFeatures: ["Solid White Oak", "Cable Management", "Soft-Close Doors", "72\" Width"],
    description: "A clean-lined media console in warm white oak that keeps your entertainment setup organized and stylish. Soft-close doors hide clutter while the integrated cable management keeps cords out of sight.",
    aspectRatio: 1.55,
    gumis: 23800,
    shares: 2615,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 36. Scented Candle (Luxury) ──────────────────────
  {
    id: "home-36",
    title: "Three-Wick Candle — Fig Tree",
    brand: "Anthropologie Home",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600&q=80",
      alt: "Three-wick candle in ceramic vessel",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=80", alt: "Three-wick candle in ceramic vessel" },
      { url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80", alt: "Candle on coffee table" },
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Candle flame detail" },
    ],
    price: { min: 4800, max: 6800, currency: "USD" },
    rating: { average: 4.8, count: 2345 },
    buyUrl: "https://anthropologie.com",
    topFeatures: ["Coconut-Soy Blend", "Three Wicks", "80-Hour Burn", "Reusable Ceramic Vessel"],
    description: "The cult-favorite candle that smells like a Mediterranean garden in summer. Notes of ripe fig, green leaf, and warm cedar fill even large rooms, and the ceramic vessel makes a gorgeous planter when the wax is gone.",
    aspectRatio: 0.90,
    gumis: 13100,
    shares: 1440,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 37. Bench ────────────────────────────────────────
  {
    id: "home-37",
    title: "Entryway Bench",
    brand: "Schoolhouse",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=600&q=80",
      alt: "Wooden entryway bench with cushion",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=1200&q=80", alt: "Wooden entryway bench with cushion" },
      { url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80", alt: "Bench in hallway" },
    ],
    price: { min: 89900, max: 119900, currency: "USD" },
    rating: { average: 4.6, count: 167 },
    buyUrl: "https://schoolhouse.com",
    topFeatures: ["Solid Maple", "48\" Width", "Wool Seat Cushion", "Made in USA"],
    description: "A Shaker-inspired bench crafted from solid maple that serves as the anchor of any entryway. The included wool cushion adds comfort and warmth to the clean, heirloom-quality design.",
    aspectRatio: 1.35,
    gumis: 6400,
    shares: 700,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 38. Oversized Vase ───────────────────────────────
  {
    id: "home-38",
    title: "Floor Vase — Matte White",
    brand: "CB2",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80",
      alt: "Large matte white floor vase",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80", alt: "Large matte white floor vase" },
      { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", alt: "Floor vase with dried palms" },
    ],
    price: { min: 12900, max: 19900, currency: "USD" },
    rating: { average: 4.5, count: 389 },
    buyUrl: "https://cb2.com",
    topFeatures: ["Earthenware", "Matte Glaze", "24\" Tall", "Watertight Interior"],
    description: "A statement floor vase in smooth matte white that instantly elevates a bare corner. Fill it with dried pampas grass, branches, or leave it empty as a sculptural accent piece.",
    aspectRatio: 0.65,
    gumis: 10700,
    shares: 1175,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 39. Cotton Waffle Towels ─────────────────────────
  {
    id: "home-39",
    title: "Waffle Bath Towel Set",
    brand: "Muji",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80",
      alt: "Folded waffle towels in bathroom",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=1200&q=80", alt: "Folded waffle towels in bathroom" },
      { url: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=1200&q=80", alt: "Towels on rack" },
    ],
    price: { min: 4800, max: 6800, currency: "USD" },
    rating: { average: 4.7, count: 912 },
    buyUrl: "https://muji.com",
    topFeatures: ["Organic Cotton Waffle", "Set of 2 Bath Towels", "Quick-Drying", "Lightweight"],
    description: "These organic cotton waffle towels are light, absorbent, and quick-drying — perfect for minimalist bathrooms. The textured weave looks elegant on a ladder rack or rolled on a shelf.",
    aspectRatio: 1.15,
    gumis: 35600,
    shares: 3915,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 40. Picture Ledge ────────────────────────────────
  {
    id: "home-40",
    title: "Picture Ledge Shelf",
    brand: "Hay",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=600&q=80",
      alt: "Picture ledge with framed prints",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=1200&q=80", alt: "Picture ledge with framed prints" },
      { url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=1200&q=80", alt: "Ledge styled with art" },
      { url: "https://images.unsplash.com/photo-1597072689227-8882273e8f6a?w=1200&q=80", alt: "Multiple ledges on wall" },
    ],
    price: { min: 5900, max: 8900, currency: "USD" },
    rating: { average: 4.5, count: 345 },
    buyUrl: "https://hay.dk",
    topFeatures: ["Powder-Coated Steel", "36\" Width", "3\" Lip", "Holds Up to 15 lbs"],
    description: "A sleek picture ledge that lets you swap out art and photos without putting new holes in the wall. The slim powder-coated steel profile adds a gallery-like feel to any room.",
    aspectRatio: 1.50,
    gumis: 27500,
    shares: 3020,
    gumiedByFriends: getRandomGumiFriends(),
  },
];
