import { Product } from "@/types";
import { getRandomGumiFriends } from "../mock-users";


export const JEWELRY_PRODUCTS: Product[] = [
  {
    id: "jewelry-1",
    title: "Gold Vermeil Hoops",
    brand: "Mejuri",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
      alt: "Gold vermeil hoop earrings on a marble surface",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&q=80", alt: "Gold vermeil hoops close-up" },
      { url: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=1200&q=80", alt: "Gold vermeil hoops on model" }
    ],
    price: { min: 5500, max: 7500, currency: "USD" },
    rating: { average: 4.7, count: 2340 },
    buyUrl: "https://mejuri.com/gold-vermeil-hoops",
    topFeatures: [
      "18k gold vermeil over sterling silver",
      "Lightweight everyday wear",
      "Hypoallergenic posts",
      "Hinged closure for easy wear",
    ],
    description: "Classic gold vermeil hoops that transition seamlessly from day to night. The lightweight construction and secure hinged closure make these a reliable go-to for any occasion.",
    aspectRatio: 0.85,
    gumis: 28400,
    shares: 2560,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-2",
    title: "Pearl Drop Earrings",
    brand: "Monica Vinader",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&q=80",
      alt: "Freshwater pearl drop earrings with gold hardware",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=1200&q=80", alt: "Pearl drop earrings detail" },
      { url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&q=80", alt: "Pearl drop earrings styled" },
      { url: "https://images.unsplash.com/photo-1611107683227-e9060eccd846?w=1200&q=80", alt: "Pearl drop earrings on model" }
    ],
    price: { min: 12800, max: 17500, currency: "USD" },
    rating: { average: 4.8, count: 1890 },
    buyUrl: "https://monicavinader.com/pearl-drop-earrings",
    topFeatures: [
      "Genuine freshwater baroque pearls",
      "18k gold plated sterling silver",
      "Each pearl uniquely shaped",
      "Butterfly back fastening",
    ],
    description: "Elegant freshwater pearl drops suspended from delicate gold vermeil hooks. Each pearl is uniquely shaped, making every pair one of a kind. Perfect for adding sophistication to any look.",
    aspectRatio: 1.25,
    gumis: 34700,
    shares: 3120,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-3",
    title: "Chunky Chain Bracelet",
    brand: "Laura Lombardi",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
      alt: "Chunky gold chain bracelet on wrist",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=80", alt: "Chunky chain bracelet detail" },
      { url: "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=1200&q=80", alt: "Chunky chain bracelet flat lay" }
    ],
    price: { min: 16800, max: 22000, currency: "USD" },
    rating: { average: 4.6, count: 876 },
    buyUrl: "https://lauralombardi.com/chunky-chain-bracelet",
    topFeatures: [
      "Recycled brass with 14k gold plating",
      "Bold oversized links",
      "Toggle clasp closure",
      "Made in New York",
    ],
    description: "A statement-making chunky chain bracelet crafted from recycled brass with a warm 14k gold plating. The oversized links give an effortlessly cool edge to any wrist stack.",
    aspectRatio: 1.1,
    gumis: 7200,
    shares: 650,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-4",
    title: "Classic Signet Ring",
    brand: "Mejuri",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
      alt: "Gold signet ring with polished face",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1200&q=80", alt: "Signet ring close-up" },
      { url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=1200&q=80", alt: "Signet ring on hand" }
    ],
    price: { min: 9800, max: 14800, currency: "USD" },
    rating: { average: 4.5, count: 1450 },
    buyUrl: "https://mejuri.com/signet-ring",
    topFeatures: [
      "14k solid gold",
      "Flat oval face for optional engraving",
      "Comfort fit band",
      "Available in sizes 4-10",
    ],
    description: "A timeless signet ring in 14k solid gold with a smooth, polished oval face. Wear it as a minimalist statement or get it engraved for a personal touch.",
    aspectRatio: 0.95,
    gumis: 22100,
    shares: 1990,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-5",
    title: "Layering Necklace Set",
    brand: "Gorjana",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600&q=80",
      alt: "Set of three layered gold necklaces",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&q=80", alt: "Layering necklace set styled" },
      { url: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=1200&q=80", alt: "Layering necklaces detail" },
      { url: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=1200&q=80", alt: "Layering necklaces on model" }
    ],
    price: { min: 6500, max: 9800, currency: "USD" },
    rating: { average: 4.6, count: 3210 },
    buyUrl: "https://gorjana.com/layering-necklace-set",
    topFeatures: [
      "Three-piece set at 14\", 16\", and 18\" lengths",
      "18k gold plated brass",
      "Mix of chain styles and pendants",
      "Tangle-free design",
      "Lobster clasp closures",
    ],
    description: "The ultimate layering set with three complementary necklaces at different lengths. Each chain features a different style for a curated look without the effort. Comes in a gift-ready box.",
    aspectRatio: 0.75,
    gumis: 31500,
    shares: 2835,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-6",
    title: "Tennis Bracelet",
    brand: "Ana Luisa",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1611107683227-e9060eccd846?w=600&q=80",
      alt: "Sparkling tennis bracelet with cubic zirconia stones",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1611107683227-e9060eccd846?w=1200&q=80", alt: "Tennis bracelet close-up" },
      { url: "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=1200&q=80", alt: "Tennis bracelet on wrist" }
    ],
    price: { min: 8500, max: 12000, currency: "USD" },
    rating: { average: 4.7, count: 2100 },
    buyUrl: "https://analuisa.com/tennis-bracelet",
    topFeatures: [
      "AAA cubic zirconia stones",
      "14k gold vermeil setting",
      "Box clasp with safety latch",
      "Adjustable 6.5\"-7.5\" length",
    ],
    description: "A classic tennis bracelet that sparkles without the luxury price tag. Each stone is hand-set in gold vermeil for a seamless line of brilliance around the wrist.",
    aspectRatio: 1.35,
    gumis: 14800,
    shares: 1330,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-7",
    title: "Gold Ear Cuff",
    brand: "Maria Black",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
      alt: "Minimalist gold ear cuff on ear",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1200&q=80", alt: "Gold ear cuff detail" },
      { url: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?w=1200&q=80", alt: "Gold ear cuff styled with other earrings" }
    ],
    price: { min: 8000, max: 14500, currency: "USD" },
    rating: { average: 4.4, count: 645 },
    buyUrl: "https://maria-black.com/gold-ear-cuff",
    topFeatures: [
      "Sterling silver with 22k gold plating",
      "No piercing required",
      "Adjustable grip tension",
      "Sold individually",
    ],
    description: "An architectural ear cuff that adds instant edge without a piercing. The sculptural design wraps snugly around the cartilage with an adjustable fit that stays put all day.",
    aspectRatio: 0.7,
    gumis: 5600,
    shares: 504,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-8",
    title: "Medallion Pendant Necklace",
    brand: "Alighieri",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&q=80",
      alt: "Textured gold medallion pendant on chain",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=1200&q=80", alt: "Medallion pendant detail" },
      { url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&q=80", alt: "Medallion pendant on model" },
      { url: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=1200&q=80", alt: "Medallion pendant on model" }
    ],
    price: { min: 29000, max: 39000, currency: "USD" },
    rating: { average: 4.8, count: 320 },
    buyUrl: "https://alighieri.com/medallion-pendant",
    topFeatures: [
      "24k gold plated bronze",
      "Hand-cast with organic texture",
      "Inspired by Dante's Divine Comedy",
      "20\" adjustable chain",
    ],
    description: "A richly textured medallion pendant with an artisan, almost ancient quality. Each piece is hand-cast in bronze and dipped in 24k gold, ensuring subtle variations that make it truly unique.",
    aspectRatio: 0.8,
    gumis: 21300,
    shares: 1920,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-9",
    title: "Pisa Chain Link Necklace",
    brand: "Laura Lombardi",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600&q=80",
      alt: "Thick gold chain link necklace",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=1200&q=80", alt: "Chain link necklace detail" },
      { url: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?w=1200&q=80", alt: "Chain link necklace on model" }
    ],
    price: { min: 19500, max: 27000, currency: "USD" },
    rating: { average: 4.7, count: 540 },
    buyUrl: "https://lauralombardi.com/pisa-chain-necklace",
    topFeatures: [
      "Recycled brass with 14k gold plating",
      "Chunky oval link design",
      "16\" choker length",
      "Sustainable and ethically made",
    ],
    description: "A bold chain link necklace that sits perfectly at the collarbone. Crafted from recycled brass and finished with 14k gold, it brings an Italian-inspired elegance with a modern attitude.",
    aspectRatio: 1.0,
    gumis: 8900,
    shares: 800,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-10",
    title: "Diamond Stud Earrings",
    brand: "Mejuri",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80",
      alt: "Classic diamond stud earrings in gold setting",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=1200&q=80", alt: "Diamond studs close-up" },
      { url: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?w=1200&q=80", alt: "Diamond studs on model" }
    ],
    price: { min: 19500, max: 30000, currency: "USD" },
    rating: { average: 4.9, count: 4320 },
    buyUrl: "https://mejuri.com/diamond-studs",
    topFeatures: [
      "0.10ct total weight lab-grown diamonds",
      "14k solid gold four-prong setting",
      "Push back posts",
      "Conflict-free and sustainable",
      "Comes with certificate of authenticity",
    ],
    description: "Timeless diamond studs featuring ethically sourced lab-grown diamonds in a classic four-prong 14k gold setting. These everyday essentials add a quiet sparkle that never goes out of style.",
    aspectRatio: 1.0,
    gumis: 33200,
    shares: 2990,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-11",
    title: "Pearl Choker Necklace",
    brand: "Sophie Buhai",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80",
      alt: "Classic pearl choker with gold clasp",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=1200&q=80", alt: "Pearl choker detail" },
      { url: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=80", alt: "Pearl choker styled" },
      { url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1200&q=80", alt: "Pearl choker styled" }
    ],
    price: { min: 39500, max: 58000, currency: "USD" },
    rating: { average: 4.8, count: 215 },
    buyUrl: "https://sophiebuhai.com/pearl-choker",
    topFeatures: [
      "Genuine Akoya pearls",
      "Sterling silver clasp with gold vermeil",
      "15\" choker length",
      "Hand-knotted between each pearl",
    ],
    description: "A modern interpretation of the classic pearl choker using lustrous Akoya pearls. Each pearl is individually hand-knotted on silk for durability and a luxurious drape.",
    aspectRatio: 1.45,
    gumis: 26800,
    shares: 2410,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-12",
    title: "Beaded Bracelet Stack",
    brand: "Gorjana",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&q=80",
      alt: "Colorful beaded bracelets stacked on wrist",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&q=80", alt: "Beaded bracelets detail" },
      { url: "https://images.unsplash.com/photo-1611107683227-e9060eccd846?w=1200&q=80", alt: "Beaded bracelets styled" }
    ],
    price: { min: 3800, max: 5800, currency: "USD" },
    rating: { average: 4.3, count: 1890 },
    buyUrl: "https://gorjana.com/beaded-bracelet-stack",
    topFeatures: [
      "Set of three stretch bracelets",
      "Natural gemstone beads",
      "Gold-filled accent beads",
      "One size fits most",
    ],
    description: "A playful set of three beaded bracelets featuring natural gemstones and gold-filled accents. The stretch design makes them easy to slip on and mix with your existing bracelet collection.",
    aspectRatio: 1.15,
    gumis: 18600,
    shares: 1670,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-13",
    title: "Dainty Gold Anklet",
    brand: "Catbird",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=600&q=80",
      alt: "Delicate gold chain anklet",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=1200&q=80", alt: "Gold anklet close-up" },
      { url: "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=1200&q=80", alt: "Gold anklet styled" }
    ],
    price: { min: 6800, max: 8800, currency: "USD" },
    rating: { average: 4.5, count: 980 },
    buyUrl: "https://catbirdnyc.com/gold-anklet",
    topFeatures: [
      "14k solid gold cable chain",
      "Adjustable 9\"-10\" length",
      "Spring ring clasp",
      "Handmade in Brooklyn",
    ],
    description: "A barely-there gold anklet crafted from solid 14k gold. The delicate cable chain catches the light beautifully and is sturdy enough for everyday wear, even in the shower.",
    aspectRatio: 1.5,
    gumis: 9400,
    shares: 845,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-14",
    title: "Bold Statement Ring",
    brand: "Completedworks",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&q=80",
      alt: "Sculptural gold statement ring",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=1200&q=80", alt: "Statement ring detail" },
      { url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&q=80", alt: "Statement ring on hand" },
      { url: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=1200&q=80", alt: "Statement ring on hand" }
    ],
    price: { min: 24000, max: 35000, currency: "USD" },
    rating: { average: 4.6, count: 189 },
    buyUrl: "https://completedworks.com/statement-ring",
    topFeatures: [
      "Recycled sterling silver with gold vermeil",
      "Sculptural organic form",
      "Each piece uniquely shaped",
      "Designed in London",
    ],
    description: "An artfully irregular statement ring that looks like a piece of wearable sculpture. Cast from recycled silver and finished in gold vermeil, it brings gallery-worthy design to your everyday look.",
    aspectRatio: 0.9,
    gumis: 6100,
    shares: 550,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-15",
    title: "Minimalist Bar Necklace",
    brand: "BYCHARI",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&q=80",
      alt: "Sleek gold bar pendant on fine chain",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=1200&q=80", alt: "Bar necklace detail" },
      { url: "https://images.unsplash.com/photo-1515688594390-b649af70d282?w=1200&q=80", alt: "Bar necklace on model" }
    ],
    price: { min: 9500, max: 16000, currency: "USD" },
    rating: { average: 4.7, count: 1560 },
    buyUrl: "https://bychari.com/bar-necklace",
    topFeatures: [
      "14k solid gold bar pendant",
      "Available for custom engraving",
      "16\" with 2\" extender",
      "Fine cable chain",
    ],
    description: "A clean-lined bar pendant in 14k solid gold, perfect for layering or wearing solo. Add custom engraving to make it a meaningful everyday piece that sits beautifully against the skin.",
    aspectRatio: 0.65,
    gumis: 12300,
    shares: 1110,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-16",
    title: "Huggie Hoop Earrings",
    brand: "Missoma",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1515688594390-b649af70d282?w=600&q=80",
      alt: "Small gold huggie hoop earrings",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1515688594390-b649af70d282?w=1200&q=80", alt: "Huggie hoops close-up" },
      { url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&q=80", alt: "Huggie hoops on model" }
    ],
    price: { min: 6800, max: 9500, currency: "USD" },
    rating: { average: 4.6, count: 2780 },
    buyUrl: "https://missoma.com/huggie-hoops",
    topFeatures: [
      "18k gold plated sterling silver",
      "Micro pavé cubic zirconia detail",
      "Hinged snap closure",
      "12mm diameter",
    ],
    description: "Petite huggie hoops with a row of sparkling micro pavé stones that hug the earlobe perfectly. Small enough for everyday wear yet eye-catching enough for an evening out.",
    aspectRatio: 1.0,
    gumis: 29700,
    shares: 2675,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-17",
    title: "Organic Sculptural Bangle",
    brand: "Sophie Buhai",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=600&q=80",
      alt: "Thick sculptural gold bangle bracelet",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=1200&q=80", alt: "Sculptural bangle detail" },
      { url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=1200&q=80", alt: "Sculptural bangle styled" },
      { url: "https://images.unsplash.com/photo-1599459183200-59c7687a0275?w=1200&q=80", alt: "Sculptural bangle styled" }
    ],
    price: { min: 42000, max: 62000, currency: "USD" },
    rating: { average: 4.7, count: 156 },
    buyUrl: "https://sophiebuhai.com/sculptural-bangle",
    topFeatures: [
      "Sterling silver with gold vermeil finish",
      "Organic undulating form",
      "Hinged opening for easy wear",
      "Weighty and substantial",
    ],
    description: "A sculptural bangle with an organic, fluid silhouette that wraps around the wrist like molten gold. The weighty feel and polished finish make it a conversation starter on its own.",
    aspectRatio: 1.2,
    gumis: 22400,
    shares: 2020,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-18",
    title: "Coin Pendant Necklace",
    brand: "Missoma",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&q=80",
      alt: "Gold coin pendant on delicate chain",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&q=80", alt: "Coin pendant detail" },
      { url: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=1200&q=80", alt: "Coin pendant on model" }
    ],
    price: { min: 8900, max: 12500, currency: "USD" },
    rating: { average: 4.5, count: 1980 },
    buyUrl: "https://missoma.com/coin-pendant",
    topFeatures: [
      "18k gold plated brass",
      "Ancient Roman-inspired design",
      "20\" adjustable chain",
      "Lobster clasp closure",
    ],
    description: "A textured coin pendant inspired by ancient Roman currency, hung on a fine gold chain. The vintage-feel motif adds a layer of intrigue and history to modern everyday styling.",
    aspectRatio: 0.78,
    gumis: 19800,
    shares: 1780,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-19",
    title: "Twisted Gold Ring",
    brand: "Jenny Bird",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&q=80",
      alt: "Twisted gold ring with crossover design",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=1200&q=80", alt: "Twisted ring close-up" },
      { url: "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=1200&q=80", alt: "Twisted ring on hand" }
    ],
    price: { min: 6800, max: 9500, currency: "USD" },
    rating: { average: 4.4, count: 1230 },
    buyUrl: "https://jennybird.com/twisted-ring",
    topFeatures: [
      "14k gold-dipped brass",
      "Crossover twisted band design",
      "Available in sizes 6-9",
      "Comfortable rounded edges",
    ],
    description: "A modern twisted ring where two bands gracefully cross over each other. The polished gold finish and comfortable fit make it an everyday ring you will never want to take off.",
    aspectRatio: 0.88,
    gumis: 7800,
    shares: 700,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-20",
    title: "Baroque Pearl Ring",
    brand: "Completedworks",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?w=600&q=80",
      alt: "Large baroque pearl set in gold ring",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?w=1200&q=80", alt: "Baroque pearl ring detail" },
      { url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&q=80", alt: "Baroque pearl ring on hand" },
      { url: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=1200&q=80", alt: "Baroque pearl ring styled" }
    ],
    price: { min: 28000, max: 38000, currency: "USD" },
    rating: { average: 4.7, count: 234 },
    buyUrl: "https://completedworks.com/baroque-pearl-ring",
    topFeatures: [
      "Genuine baroque freshwater pearl",
      "Recycled sterling silver band",
      "Gold vermeil finish",
      "Each pearl uniquely shaped",
    ],
    description: "A statement ring featuring a large, irregularly shaped baroque pearl cradled in a sculpted gold vermeil setting. The organic beauty of the pearl makes each ring a one-of-a-kind piece.",
    aspectRatio: 1.05,
    gumis: 5300,
    shares: 480,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-21",
    title: "Herringbone Chain Necklace",
    brand: "Ana Luisa",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=600&q=80",
      alt: "Flat herringbone gold chain necklace",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=1200&q=80", alt: "Herringbone chain detail" },
      { url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1200&q=80", alt: "Herringbone chain on model" }
    ],
    price: { min: 5500, max: 8500, currency: "USD" },
    rating: { average: 4.6, count: 3450 },
    buyUrl: "https://analuisa.com/herringbone-necklace",
    topFeatures: [
      "Recycled gold vermeil",
      "Flat, fluid drape",
      "16\" with 2\" extender",
      "Carbon-neutral production",
    ],
    description: "A silky-smooth herringbone chain that drapes flat against the skin for a liquid gold effect. Made from recycled gold vermeil as part of Ana Luisa's carbon-neutral commitment.",
    aspectRatio: 0.72,
    gumis: 11200,
    shares: 1010,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-22",
    title: "Crawler Ear Climbers",
    brand: "Adina Reyter",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1599459183200-59c7687a0275?w=600&q=80",
      alt: "Diamond ear climber earrings",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1599459183200-59c7687a0275?w=1200&q=80", alt: "Ear climbers detail" },
      { url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1200&q=80", alt: "Ear climbers on model" }
    ],
    price: { min: 29800, max: 42000, currency: "USD" },
    rating: { average: 4.8, count: 412 },
    buyUrl: "https://adinareyter.com/ear-climbers",
    topFeatures: [
      "14k solid gold setting",
      "Graduated pave diamonds",
      "Comfortable post back",
      "Designed to follow the ear curve",
    ],
    description: "Sleek ear climbers that trace the curve of the earlobe with a trail of graduated pave diamonds. Set in 14k solid gold, they give the look of multiple earrings with just one piercing.",
    aspectRatio: 0.68,
    gumis: 41600,
    shares: 3745,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-23",
    title: "Chunky Open Cuff",
    brand: "Jenny Bird",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600&q=80",
      alt: "Wide gold open cuff bracelet",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&q=80", alt: "Open cuff detail" },
      { url: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=1200&q=80", alt: "Open cuff on wrist" },
      { url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=1200&q=80", alt: "Open cuff on wrist" }
    ],
    price: { min: 8500, max: 12800, currency: "USD" },
    rating: { average: 4.5, count: 876 },
    buyUrl: "https://jennybird.com/chunky-cuff",
    topFeatures: [
      "14k gold-dipped brass",
      "Open-ended design for adjustable fit",
      "Smooth polished finish",
      "Lightweight despite bold size",
    ],
    description: "A wide, polished gold cuff that commands attention without feeling heavy. The open-ended design allows you to adjust the fit, and the tapered edges keep the look refined.",
    aspectRatio: 1.3,
    gumis: 4900,
    shares: 440,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-24",
    title: "Satellite Chain Necklace",
    brand: "Catbird",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&q=80",
      alt: "Delicate satellite chain with tiny gold beads",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=1200&q=80", alt: "Satellite chain detail" },
      { url: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=1200&q=80", alt: "Satellite chain layered" }
    ],
    price: { min: 7400, max: 10200, currency: "USD" },
    rating: { average: 4.6, count: 1670 },
    buyUrl: "https://catbirdnyc.com/satellite-chain",
    topFeatures: [
      "14k solid gold chain and beads",
      "Tiny bead stations every half inch",
      "16\" with 1\" extender",
      "Handmade in NYC",
    ],
    description: "A whisper-thin gold chain dotted with tiny gold bead stations that catch the light as you move. Handcrafted in Brooklyn from solid 14k gold for a necklace that lasts a lifetime.",
    aspectRatio: 0.82,
    gumis: 8300,
    shares: 750,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-25",
    title: "Lion Head Pendant",
    brand: "Alighieri",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&q=80",
      alt: "Textured lion head gold pendant necklace",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=1200&q=80", alt: "Lion pendant detail" },
      { url: "https://images.unsplash.com/photo-1515688594390-b649af70d282?w=1200&q=80", alt: "Lion pendant styled" }
    ],
    price: { min: 35000, max: 45000, currency: "USD" },
    rating: { average: 4.9, count: 198 },
    buyUrl: "https://alighieri.com/lion-pendant",
    topFeatures: [
      "24k gold plated bronze",
      "Hand-finished textured detail",
      "22\" rope chain included",
      "Inspired by Dante's Inferno",
      "Comes in signature velvet pouch",
    ],
    description: "A richly detailed lion head pendant that channels old-world symbolism through a contemporary lens. Hand-cast in bronze and finished in 24k gold, each piece carries slight variations that tell its own story.",
    aspectRatio: 0.75,
    gumis: 27500,
    shares: 2475,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-26",
    title: "Pave Diamond Huggies",
    brand: "Adina Reyter",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?w=600&q=80",
      alt: "Small diamond pave huggie earrings",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?w=1200&q=80", alt: "Pave huggies close-up" },
      { url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=1200&q=80", alt: "Pave huggies on model" },
      { url: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?w=1200&q=80", alt: "Pave huggies on model" }
    ],
    price: { min: 35000, max: 48000, currency: "USD" },
    rating: { average: 4.8, count: 567 },
    buyUrl: "https://adinareyter.com/pave-huggies",
    topFeatures: [
      "14k solid gold",
      "Full pave natural diamonds",
      "Hinged snap closure",
      "10mm diameter",
    ],
    description: "Petite huggie hoops encrusted with natural pave diamonds in 14k solid gold. They deliver maximum sparkle in a minimal, sleep-in-them-comfortable size.",
    aspectRatio: 1.1,
    gumis: 48200,
    shares: 4340,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-27",
    title: "Curb Chain Bracelet",
    brand: "Missoma",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=600&q=80",
      alt: "Gold curb chain bracelet",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=1200&q=80", alt: "Curb chain bracelet detail" },
      { url: "https://images.unsplash.com/photo-1599459183200-59c7687a0275?w=1200&q=80", alt: "Curb chain bracelet on wrist" }
    ],
    price: { min: 7800, max: 10500, currency: "USD" },
    rating: { average: 4.5, count: 2100 },
    buyUrl: "https://missoma.com/curb-chain-bracelet",
    topFeatures: [
      "18k gold plated recycled silver",
      "Classic curb link pattern",
      "T-bar toggle closure",
      "Available in 6.5\" and 7\" lengths",
    ],
    description: "A versatile curb chain bracelet with a satisfying weight and a chic T-bar toggle. Perfect worn alone for a polished look or stacked with other bracelets for a curated arm party.",
    aspectRatio: 1.4,
    gumis: 23600,
    shares: 2125,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-28",
    title: "Pearl Strand Bracelet",
    brand: "Monica Vinader",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=600&q=80",
      alt: "Freshwater pearl strand bracelet with gold clasp",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=1200&q=80", alt: "Pearl bracelet detail" },
      { url: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=1200&q=80", alt: "Pearl bracelet on wrist" }
    ],
    price: { min: 15000, max: 22000, currency: "USD" },
    rating: { average: 4.6, count: 890 },
    buyUrl: "https://monicavinader.com/pearl-bracelet",
    topFeatures: [
      "Genuine freshwater pearls",
      "18k gold vermeil adjustable clasp",
      "Silk thread knotting",
      "Adjustable slider closure",
    ],
    description: "A refined pearl strand bracelet featuring hand-selected freshwater pearls on silk thread. The modern slider clasp in gold vermeil allows for a perfect fit on any wrist size.",
    aspectRatio: 1.55,
    gumis: 31800,
    shares: 2860,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-29",
    title: "Dome Ring",
    brand: "Mejuri",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?w=600&q=80",
      alt: "Polished gold dome ring",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1598560917807-1bae44bd2be8?w=1200&q=80", alt: "Dome ring close-up" },
      { url: "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=1200&q=80", alt: "Dome ring on hand" },
      { url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200&q=80", alt: "Dome ring on hand" }
    ],
    price: { min: 7500, max: 12500, currency: "USD" },
    rating: { average: 4.5, count: 2340 },
    buyUrl: "https://mejuri.com/dome-ring",
    topFeatures: [
      "14k solid gold",
      "Smooth domed silhouette",
      "Comfort fit interior",
      "Available in sizes 4-10",
    ],
    description: "A sleek, rounded dome ring in solid 14k gold that sits beautifully on the finger. The polished surface reflects light from every angle, creating a bold yet refined look.",
    aspectRatio: 0.92,
    gumis: 17400,
    shares: 1565,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-30",
    title: "Emerald Bezel Studs",
    brand: "Wwake",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&q=80",
      alt: "Small emerald bezel-set stud earrings",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=1200&q=80", alt: "Emerald studs detail" },
      { url: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=1200&q=80", alt: "Emerald studs on model" }
    ],
    price: { min: 38000, max: 52000, currency: "USD" },
    rating: { average: 4.9, count: 178 },
    buyUrl: "https://wwake.com/emerald-studs",
    topFeatures: [
      "Natural emerald gemstones",
      "14k solid yellow gold bezel",
      "Post with butterfly back",
      "Ethically sourced stones",
      "Handmade in New York",
    ],
    description: "Vivid natural emeralds encased in smooth 14k gold bezels for a refined, modern take on colored gemstone studs. Each stone is hand-selected for its rich green hue and exceptional clarity.",
    aspectRatio: 0.95,
    gumis: 38900,
    shares: 3500,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-31",
    title: "Figaro Chain Necklace",
    brand: "Laura Lombardi",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
      alt: "Gold figaro chain necklace with mixed link sizes",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1200&q=80", alt: "Figaro chain detail" },
      { url: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=1200&q=80", alt: "Figaro chain styled" }
    ],
    price: { min: 14500, max: 19500, currency: "USD" },
    rating: { average: 4.6, count: 430 },
    buyUrl: "https://lauralombardi.com/figaro-chain",
    topFeatures: [
      "Recycled brass with 14k gold plating",
      "Alternating short and long links",
      "18\" length",
      "Spring ring clasp",
    ],
    description: "A classic figaro chain with its signature pattern of alternating short and elongated links. Made from recycled brass and plated in 14k gold for a sustainable take on a timeless silhouette.",
    aspectRatio: 0.85,
    gumis: 6700,
    shares: 605,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-32",
    title: "Croissant Dome Earrings",
    brand: "Jenny Bird",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=600&q=80",
      alt: "Croissant-shaped gold dome earrings",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=1200&q=80", alt: "Croissant earrings detail" },
      { url: "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=1200&q=80", alt: "Croissant earrings on model" },
      { url: "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=1200&q=80", alt: "Croissant earrings styling" }
    ],
    price: { min: 6500, max: 8800, currency: "USD" },
    rating: { average: 4.4, count: 1560 },
    buyUrl: "https://jennybird.com/croissant-earrings",
    topFeatures: [
      "14k gold-dipped brass",
      "Twisted croissant texture",
      "Post back with large butterfly clutch",
      "Lightweight hollow construction",
    ],
    description: "Playful, croissant-textured dome earrings that bring sculptural energy to any outfit. The hollow construction keeps them surprisingly light despite their substantial, eye-catching size.",
    aspectRatio: 1.08,
    gumis: 9100,
    shares: 820,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-33",
    title: "Initial Pendant Necklace",
    brand: "BYCHARI",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1625794084867-8ddd239946b1?w=600&q=80",
      alt: "Gold initial letter pendant on fine chain",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1625794084867-8ddd239946b1?w=1200&q=80", alt: "Initial pendant detail" },
      { url: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=1200&q=80", alt: "Initial pendant on model" }
    ],
    price: { min: 12500, max: 18000, currency: "USD" },
    rating: { average: 4.7, count: 2890 },
    buyUrl: "https://bychari.com/initial-pendant",
    topFeatures: [
      "14k solid gold letter pendant",
      "All 26 letters available",
      "16\" fine cable chain",
      "Handmade to order",
    ],
    description: "A delicate solid gold initial pendant that sits close to the heart. Made famous on the red carpet, this everyday necklace adds a personal, meaningful touch to any neckline.",
    aspectRatio: 0.7,
    gumis: 15600,
    shares: 1405,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-34",
    title: "Mixed Metal Stacking Rings",
    brand: "Maria Black",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1583292650898-7d22cd27ca6f?w=600&q=80",
      alt: "Set of thin gold and silver stacking rings",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1583292650898-7d22cd27ca6f?w=1200&q=80", alt: "Stacking rings detail" },
      { url: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=1200&q=80", alt: "Stacking rings on hand" }
    ],
    price: { min: 9500, max: 16500, currency: "USD" },
    rating: { average: 4.5, count: 920 },
    buyUrl: "https://maria-black.com/stacking-rings",
    topFeatures: [
      "Set of 3 rings in mixed metals",
      "Sterling silver, gold plated, and rose gold",
      "1mm to 2mm widths",
      "Available in sizes 5-9",
    ],
    description: "A curated set of three stacking rings in mixed metals that are meant to be worn together or spread across multiple fingers. The varying widths and finishes create a perfectly imperfect look.",
    aspectRatio: 0.98,
    gumis: 4200,
    shares: 380,
    gumiedByFriends: getRandomGumiFriends(),
  },
  {
    id: "jewelry-35",
    title: "Rope Chain Choker",
    brand: "Gorjana",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=600&q=80",
      alt: "Twisted rope chain gold choker necklace",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=1200&q=80", alt: "Rope chain choker detail" },
      { url: "https://images.unsplash.com/photo-1610694955371-d4a3e0ce4b52?w=1200&q=80", alt: "Rope chain choker on model" },
      { url: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=1200&q=80", alt: "Rope chain choker on model" }
    ],
    price: { min: 5500, max: 7500, currency: "USD" },
    rating: { average: 4.4, count: 1890 },
    buyUrl: "https://gorjana.com/rope-choker",
    topFeatures: [
      "18k gold plated brass",
      "Twisted rope texture",
      "14\" with 3\" extender",
      "Lobster clasp closure",
    ],
    description: "A textured rope chain choker that sits elegantly at the base of the neck. The twisted design adds visual interest and dimension, making it a standout layering piece or solo statement.",
    aspectRatio: 1.48,
    gumis: 13900,
    shares: 1250,
    gumiedByFriends: getRandomGumiFriends(),
  },
];
