import { Product } from "@/types";
import { getRandomGumiFriends } from "../mock-users";


export const KITCHEN_PRODUCTS: Product[] = [
  // ─── 1. Fellow Stagg EKG Pour-Over Kettle ─────────────
  {
    id: "kitchen-1",
    title: "Stagg EKG Electric Pour-Over Kettle",
    brand: "Fellow",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
      alt: "Matte black gooseneck kettle on counter",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80", alt: "Matte black gooseneck kettle on counter" },
      { url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80", alt: "Pour-over coffee setup" },
    ],
    price: { min: 16500, max: 16500, currency: "USD" },
    rating: { average: 4.8, count: 2341 },
    buyUrl: "https://fellowproducts.com",
    topFeatures: ["Variable Temperature Control", "Precision Pour Spout", "Hold Mode Up to 60 Min", "LCD Display", "900ml Capacity"],
    description: "The kettle that changed the pour-over game. Fellow's Stagg EKG delivers pinpoint temperature accuracy with a counterbalanced handle and slow-pour spout that gives you total control over your brew. Looks as stunning on the counter as it performs in the morning ritual.",
    aspectRatio: 1.15,
    gumis: 6800,
    shares: 748,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 2. Le Creuset Dutch Oven ──────────────────────────
  {
    id: "kitchen-2",
    title: "Signature Round Dutch Oven 5.5 Qt",
    brand: "Le Creuset",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80",
      alt: "Vibrant enameled Dutch oven on stovetop",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80", alt: "Vibrant enameled Dutch oven on stovetop" },
      { url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80", alt: "Dutch oven with fresh bread inside" },
    ],
    price: { min: 37500, max: 37500, currency: "USD" },
    rating: { average: 4.9, count: 4872 },
    buyUrl: "https://lecreuset.com",
    topFeatures: ["Enameled Cast Iron", "Tight-Fitting Lid", "Oven Safe to 500F", "Dishwasher Safe", "Lifetime Warranty"],
    description: "The icon of the kitchen for a reason. Le Creuset's Signature Dutch Oven distributes heat slowly and evenly, locking in moisture for braises, soups, and the crustiest artisan bread you'll ever bake at home. Passed down through generations and somehow still the most beautiful thing on the shelf.",
    aspectRatio: 0.95,
    gumis: 89000,
    shares: 9790,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 3. Miyabi Birchwood Chef's Knife ─────────────────
  {
    id: "kitchen-3",
    title: "Birchwood SG2 8-Inch Chef's Knife",
    brand: "Miyabi",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80",
      alt: "Japanese chef knife on wooden cutting board",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80", alt: "Japanese chef knife on wooden cutting board" },
      { url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1200&q=80", alt: "Knife with fresh herbs prep" },
    ],
    price: { min: 27500, max: 27500, currency: "USD" },
    rating: { average: 4.9, count: 634 },
    buyUrl: "https://miyabi.zwilling.com",
    topFeatures: ["SG2 Micro-Carbide Steel", "101-Layer Damascus Pattern", "Birchwood Handle", "9.5-12 Degree Edge", "Ice-Hardened FRIODUR Blade"],
    description: "A knife forged in the centuries-old Seki tradition, where precision meets artistry. The SG2 steel holds its razor edge far longer than conventional blades, while the 101-layer Damascus flower pattern makes every slice feel ceremonial. The birchwood handle warms to your grip like it was made for you.",
    aspectRatio: 1.45,
    gumis: 24500,
    shares: 2695,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 4. Our Place Always Pan ───────────────────────────
  {
    id: "kitchen-4",
    title: "Always Pan 2.0",
    brand: "Our Place",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=600&q=80",
      alt: "Terracotta ceramic pan with steamer insert",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1200&q=80", alt: "Terracotta ceramic pan with steamer insert" },
      { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=1200&q=80", alt: "Pan with sauteed vegetables" },
    ],
    price: { min: 14900, max: 14900, currency: "USD" },
    rating: { average: 4.5, count: 3201 },
    buyUrl: "https://fromourplace.com",
    topFeatures: ["Replaces 8 Pieces of Cookware", "Toxin-Free Ceramic Coating", "Built-In Steamer Basket", "Nesting Beechwood Spatula", "Stainless Steel Steaming Rack"],
    description: "The pan that launched a thousand kitchen declutters. Our Place's Always Pan does the work of a fry pan, saute pan, steamer, skillet, saucier, non-stick pan, spatula, and spoon rest all in one beautifully designed piece. Less clutter, more cooking, way better aesthetic.",
    aspectRatio: 0.85,
    gumis: 72000,
    shares: 7920,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 5. Hasami Porcelain Dinnerware Set ────────────────
  {
    id: "kitchen-5",
    title: "Stackable Dinnerware Set — Natural",
    brand: "Hasami Porcelain",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80",
      alt: "Minimalist stacked ceramic plates and bowls",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=1200&q=80", alt: "Minimalist stacked ceramic plates and bowls" },
      { url: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=1200&q=80", alt: "Table setting with ceramic dinnerware" },
    ],
    price: { min: 18000, max: 32000, currency: "USD" },
    rating: { average: 4.7, count: 412 },
    buyUrl: "https://hasami-porcelain.com",
    topFeatures: ["Porcelain from Hasami, Japan", "Modular Stacking Design", "Microwave & Dishwasher Safe", "Matte Unglazed Exterior"],
    description: "Born in Hasami, Japan, where porcelain has been crafted for over 400 years. Each piece is designed to stack seamlessly with any other, turning your cupboard into a perfectly ordered grid. The raw, unglazed exterior feels like holding a smooth river stone.",
    aspectRatio: 1.0,
    gumis: 4200,
    shares: 462,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 6. East Fork Mug ─────────────────────────────────
  {
    id: "kitchen-6",
    title: "The Mug — Panna Cotta",
    brand: "East Fork",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&q=80",
      alt: "Speckled ceramic mug with coffee",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=1200&q=80", alt: "Speckled ceramic mug with coffee" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80", alt: "Hand holding speckled mug" },
    ],
    price: { min: 3800, max: 3800, currency: "USD" },
    rating: { average: 4.8, count: 1247 },
    buyUrl: "https://eastfork.com",
    topFeatures: ["Handmade in Asheville, NC", "Lead & Cadmium Free Glaze", "Microwave & Dishwasher Safe", "10 oz Capacity"],
    description: "The mug people camp overnight online to buy. East Fork's signature silhouette fits perfectly in the hand, with a generous handle and a foot that stays cool on the table. The Panna Cotta glaze breaks beautifully over the curves, making every mug uniquely yours.",
    aspectRatio: 0.75,
    gumis: 7800,
    shares: 858,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 7. Material Kitchen Olive Wood Board ──────────────
  {
    id: "kitchen-7",
    title: "The Olive Wood Cutting Board",
    brand: "Material Kitchen",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
      alt: "Olive wood cutting board with artisan bread and cheese",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80", alt: "Olive wood cutting board with bread and cheese" },
      { url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1200&q=80", alt: "Board styled for entertaining" },
    ],
    price: { min: 7500, max: 7500, currency: "USD" },
    rating: { average: 4.6, count: 289 },
    buyUrl: "https://materialkitchen.com",
    topFeatures: ["Sustainably Sourced Olive Wood", "Natural Grain Variations", "Doubles as Serving Board", "Knife-Friendly Surface"],
    description: "Every board is a one-of-one, shaped by the natural grain and knots of Mediterranean olive wood. Gentle on knife edges yet durable enough for daily prep, it transitions effortlessly from kitchen workhorse to stunning charcuterie presentation.",
    aspectRatio: 1.35,
    gumis: 3100,
    shares: 341,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 8. Chemex Pour-Over Coffeemaker ──────────────────
  {
    id: "kitchen-8",
    title: "Classic Series 8-Cup Pour-Over",
    brand: "Chemex",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&q=80",
      alt: "Chemex glass coffeemaker with wood collar",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1200&q=80", alt: "Chemex glass coffeemaker with wood collar" },
      { url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=1200&q=80", alt: "Pour-over brewing in progress" },
    ],
    price: { min: 4750, max: 4750, currency: "USD" },
    rating: { average: 4.7, count: 3687 },
    buyUrl: "https://chemex.com",
    topFeatures: ["Borosilicate Glass", "Polished Wood Collar & Tie", "MoMA Permanent Collection", "BPA-Free", "Makes 8 Cups"],
    description: "Designed in 1941 and still the most beautiful object on any coffee lover's counter. The Chemex is in the permanent collection at MoMA for good reason: its hourglass silhouette and wood collar are as iconic as the clean, bright cup it produces.",
    aspectRatio: 1.55,
    gumis: 5600,
    shares: 616,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 9. Staub Cocotte ─────────────────────────────────
  {
    id: "kitchen-9",
    title: "Round Cocotte 4 Qt — Black Matte",
    brand: "Staub",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80",
      alt: "Black matte cast iron cocotte with lid",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=1200&q=80", alt: "Black matte cast iron cocotte with lid" },
      { url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=1200&q=80", alt: "Cocotte with braised short ribs" },
    ],
    price: { min: 35000, max: 35000, currency: "USD" },
    rating: { average: 4.8, count: 1842 },
    buyUrl: "https://staubusa.com",
    topFeatures: ["Enameled Cast Iron", "Self-Basting Spike Lid", "Black Matte Enamel Interior", "Oven Safe to 500F", "Made in France"],
    description: "Staub's signature spike-studded lid continuously bastes your dish in its own juices, creating layers of flavor no other pot can match. The black matte enamel interior develops a natural patina over time, getting better with every braise, roast, and bake.",
    aspectRatio: 0.9,
    gumis: 67000,
    shares: 7370,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 10. Riedel Wine Glasses ──────────────────────────
  {
    id: "kitchen-10",
    title: "Veritas Cabernet/Merlot Glass Set of 2",
    brand: "Riedel",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=600&q=80",
      alt: "Crystal wine glasses catching light",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=1200&q=80", alt: "Crystal wine glasses catching light" },
      { url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=1200&q=80", alt: "Wine glasses on dinner table" },
    ],
    price: { min: 6500, max: 6500, currency: "USD" },
    rating: { average: 4.7, count: 1534 },
    buyUrl: "https://riedel.com",
    topFeatures: ["Machine-Blown Crystal", "Varietal-Specific Bowl Shape", "Extremely Thin Rim", "Dishwasher Safe", "Set of 2"],
    description: "Riedel literally wrote the science on how glass shape affects wine flavor. The Veritas Cabernet bowl is engineered to direct wine precisely where your palate perceives boldness and fruit, transforming even a Tuesday night pour into something ceremonial.",
    aspectRatio: 1.4,
    gumis: 4800,
    shares: 528,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 11. Heath Ceramics Serving Platter ───────────────
  {
    id: "kitchen-11",
    title: "Rim Line Oval Serving Platter",
    brand: "Heath Ceramics",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&q=80",
      alt: "Handcrafted ceramic serving platter",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=1200&q=80", alt: "Handcrafted ceramic serving platter" },
      { url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80", alt: "Platter in kitchen setting" },
    ],
    price: { min: 14000, max: 14000, currency: "USD" },
    rating: { average: 4.8, count: 198 },
    buyUrl: "https://heathceramics.com",
    topFeatures: ["Handmade in Sausalito, CA", "Lead-Free Glaze", "Oven & Microwave Safe", "15-Inch Oval"],
    description: "Handmade in Sausalito since 1948, Heath's Rim Line platter is the quiet centerpiece of every gathering. The subtle rim catches sauces and juices while the reactive glaze ensures no two platters are exactly alike. It's the piece guests always ask about.",
    aspectRatio: 0.7,
    gumis: 2900,
    shares: 319,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 12. Le Creuset Cast Iron Skillet ─────────────────
  {
    id: "kitchen-12",
    title: "Signature Iron Handle Skillet 10.25\"",
    brand: "Le Creuset",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
      alt: "Enameled cast iron skillet with seared steak",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80", alt: "Enameled cast iron skillet with seared steak" },
      { url: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=1200&q=80", alt: "Skillet on induction cooktop" },
    ],
    price: { min: 18500, max: 18500, currency: "USD" },
    rating: { average: 4.8, count: 2107 },
    buyUrl: "https://lecreuset.com",
    topFeatures: ["Enameled Cast Iron", "Satin Black Interior", "Helper Handle", "Oven Safe to 500F", "Pour Spouts"],
    description: "The sear you get from Le Creuset's satin black enamel interior is unmatched — caramelized, crackling, and perfectly even. Unlike raw cast iron, the enamel never needs seasoning and cleans up in minutes. Built to outlast every trend and every pan that tries to replace it.",
    aspectRatio: 1.05,
    gumis: 81000,
    shares: 8910,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 13. Hario V60 Pour-Over Dripper ──────────────────
  {
    id: "kitchen-13",
    title: "V60 Ceramic Pour-Over Dripper 02",
    brand: "Hario",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=600&q=80",
      alt: "White ceramic V60 dripper with coffee bloom",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=1200&q=80", alt: "White ceramic V60 dripper with coffee bloom" },
      { url: "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80", alt: "V60 brewing setup" },
    ],
    price: { min: 2900, max: 2900, currency: "USD" },
    rating: { average: 4.7, count: 4231 },
    buyUrl: "https://hario-usa.com",
    topFeatures: ["Arita-Ware Ceramic", "60-Degree Angle Cone", "Spiral Ribbed Interior", "Single Large Drain Hole", "Brews 1-4 Cups"],
    description: "The dripper that specialty coffee was built on. Hario's signature 60-degree angle and spiral ribs allow you to control extraction speed by adjusting your pour, making it the most versatile manual brewer ever designed. The ceramic version retains heat beautifully for a cleaner cup.",
    aspectRatio: 0.8,
    gumis: 5100,
    shares: 561,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 14. Hedley & Bennett Cocktail Shaker ─────────────
  {
    id: "kitchen-14",
    title: "Brass-Finished Cocktail Shaker",
    brand: "Hedley & Bennett",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
      alt: "Brass cocktail shaker on bar cart",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=80", alt: "Brass cocktail shaker on bar cart" },
      { url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200&q=80", alt: "Shaker with mixed cocktail" },
    ],
    price: { min: 5500, max: 5500, currency: "USD" },
    rating: { average: 4.5, count: 347 },
    buyUrl: "https://hedleyandbennett.com",
    topFeatures: ["Brushed Brass Finish", "Built-In Strainer", "28 oz Capacity", "Weighted Base", "Develops Patina Over Time"],
    description: "A bar cart essential that gets more beautiful with age. The brushed brass develops a rich, living patina that tells the story of every cocktail hour. Weighted at the base for a confident shake, with a built-in strainer that pours clean every time.",
    aspectRatio: 1.5,
    gumis: 11200,
    shares: 1232,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 15. Material Kitchen Linen Napkin Set ────────────
  {
    id: "kitchen-15",
    title: "Linen Napkin Set of 4 — Flax",
    brand: "Material Kitchen",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80",
      alt: "Natural linen napkins on styled table",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200&q=80", alt: "Natural linen napkins on styled table" },
      { url: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=1200&q=80", alt: "Napkins with place setting" },
    ],
    price: { min: 4200, max: 4200, currency: "USD" },
    rating: { average: 4.6, count: 521 },
    buyUrl: "https://materialkitchen.com",
    topFeatures: ["100% European Linen", "Stonewashed Softness", "Set of 4", "OEKO-TEX Certified", "20\" x 20\""],
    description: "Paper napkins are over. Material's stonewashed linen set arrives impossibly soft from day one and only gets better with each wash. The natural flax color complements every table setting, from weeknight pasta to full-production dinner parties.",
    aspectRatio: 0.68,
    gumis: 3600,
    shares: 396,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 16. Fellow French Press ──────────────────────────
  {
    id: "kitchen-16",
    title: "Clara French Press",
    brand: "Fellow",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&q=80",
      alt: "Modern matte black French press",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=1200&q=80", alt: "Modern matte black French press" },
      { url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=1200&q=80", alt: "French press with coffee cups" },
    ],
    price: { min: 8900, max: 8900, currency: "USD" },
    rating: { average: 4.6, count: 892 },
    buyUrl: "https://fellowproducts.com",
    topFeatures: ["Enhanced Filtration System", "Double-Wall Insulation", "Non-Slip Base", "24 oz Capacity", "Matte Black or Warm White"],
    description: "Fellow re-engineered the French press from the ground up. The enhanced filtration system catches micro-grounds that other presses miss, giving you the full-bodied richness of immersion brewing without the grit. Double-wall vacuum insulation keeps it hot for 4x longer.",
    aspectRatio: 1.2,
    gumis: 7200,
    shares: 792,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 17. Emile Henry Mortar & Pestle ──────────────────
  {
    id: "kitchen-17",
    title: "Ceramic Mortar & Pestle",
    brand: "Emile Henry",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
      alt: "Textured ceramic mortar with fresh herbs",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=1200&q=80", alt: "Textured ceramic mortar with fresh herbs" },
      { url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=1200&q=80", alt: "Mortar and pestle on wooden counter" },
    ],
    price: { min: 5500, max: 5500, currency: "USD" },
    rating: { average: 4.5, count: 276 },
    buyUrl: "https://emilehenryusa.com",
    topFeatures: ["HR Ceramic", "Unglazed Interior for Grip", "Non-Slip Silicone Base", "Made in France", "Dishwasher Safe"],
    description: "The French know a thing or two about grinding spices. Emile Henry's ceramic mortar features a deliberately unglazed interior that grips and grinds without the weight of traditional stone. The silicone base keeps it planted while you crush peppercorns, make pesto, or muddle herbs.",
    aspectRatio: 0.88,
    gumis: 2400,
    shares: 264,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 18. East Fork Pasta Bowl Set ─────────────────────
  {
    id: "kitchen-18",
    title: "Everyday Bowl Set of 4 — Morel",
    brand: "East Fork",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80",
      alt: "Stoneware pasta bowls in warm earth tones",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=1200&q=80", alt: "Stoneware pasta bowls in warm earth tones" },
      { url: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80", alt: "Bowl with fresh pasta" },
    ],
    price: { min: 14400, max: 14400, currency: "USD" },
    rating: { average: 4.8, count: 687 },
    buyUrl: "https://eastfork.com",
    topFeatures: ["Handmade Stoneware", "Generous 24 oz Capacity", "Set of 4", "Microwave & Dishwasher Safe", "Lead & Cadmium Free"],
    description: "The bowl that makes ramen night, pasta night, and cereal-for-dinner night all feel intentional. East Fork's Everyday Bowl is generously sized to cradle a proper portion with room for broth, and the Morel glaze breaks into earthy, warm tones that make food look incredible.",
    aspectRatio: 1.1,
    gumis: 6400,
    shares: 704,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 19. GreenPan Mixing Bowl Set ─────────────────────
  {
    id: "kitchen-19",
    title: "Stainless Steel Mixing Bowl Set",
    brand: "GreenPan",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&q=80",
      alt: "Nested stainless steel mixing bowls",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80", alt: "Nested stainless steel mixing bowls" },
      { url: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80", alt: "Bowls during baking prep" },
    ],
    price: { min: 5500, max: 5500, currency: "USD" },
    rating: { average: 4.4, count: 812 },
    buyUrl: "https://greenpan.us",
    topFeatures: ["18/8 Stainless Steel", "Non-Slip Silicone Bases", "Measurement Markings", "Set of 3 (1.5, 3, 5 Qt)", "Dishwasher Safe"],
    description: "The workhorse set every kitchen actually needs. GreenPan's mixing bowls nest cleanly, stay put with silicone bases, and feature interior measurement markings so you can eyeball quantities without dirtying another cup. Stainless steel won't stain from turmeric or tomato.",
    aspectRatio: 0.78,
    gumis: 9800,
    shares: 1078,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 20. Wusthof Knife Set ────────────────────────────
  {
    id: "kitchen-20",
    title: "Classic 7-Piece Knife Block Set",
    brand: "Wusthof",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&q=80",
      alt: "German knife set in walnut block",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80", alt: "German knife set in walnut block" },
      { url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=1200&q=80", alt: "Knife set on kitchen counter" },
    ],
    price: { min: 49900, max: 49900, currency: "USD" },
    rating: { average: 4.8, count: 1923 },
    buyUrl: "https://wusthof.com",
    topFeatures: ["Precision-Forged German Steel", "Full Tang Construction", "Triple-Riveted Handles", "17-Slot Walnut Block", "Lifetime Warranty"],
    description: "Seven generations of Solingen knifemaking in one block. Every Wusthof Classic blade is precision-forged from a single piece of high-carbon stainless steel, with a full tang and triple-riveted handle that feels perfectly balanced. The walnut block is a kitchen counter monument.",
    aspectRatio: 1.3,
    gumis: 38000,
    shares: 4180,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 21. Vitamix Blender ──────────────────────────────
  {
    id: "kitchen-21",
    title: "A3500 Ascent Series Blender",
    brand: "Vitamix",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80",
      alt: "Sleek stainless steel Vitamix blender",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=1200&q=80", alt: "Sleek stainless steel Vitamix blender" },
      { url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&q=80", alt: "Blender with smoothie ingredients" },
    ],
    price: { min: 64995, max: 64995, currency: "USD" },
    rating: { average: 4.9, count: 3456 },
    buyUrl: "https://vitamix.com",
    topFeatures: ["2.2 HP Motor", "Touchscreen Controls", "5 Program Settings", "Self-Cleaning Cycle", "10-Year Warranty"],
    description: "The blender that makes every other blender feel like a toy. Vitamix's 2.2 horsepower motor pulverizes anything from frozen acai to hot soup in seconds. The touchscreen interface and built-in programs mean perfect results without babysitting. You'll have this for a decade.",
    aspectRatio: 1.48,
    gumis: 52000,
    shares: 5720,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 22. Mauviel Copper Saucepan ──────────────────────
  {
    id: "kitchen-22",
    title: "M'Heritage M150B 1.9 Qt Saucepan",
    brand: "Mauviel",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
      alt: "Gleaming copper saucepan with brass handle",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&q=80", alt: "Gleaming copper saucepan with brass handle" },
      { url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&q=80", alt: "Copper pan on gas range" },
    ],
    price: { min: 30000, max: 30000, currency: "USD" },
    rating: { average: 4.9, count: 234 },
    buyUrl: "https://mauviel.com",
    topFeatures: ["1.5mm Copper Construction", "Stainless Steel Lining", "Cast Iron Handle", "Made in Villedieu, France", "Induction Compatible"],
    description: "Copper isn't just for show — it conducts heat 25x faster than stainless steel, giving you surgical control over temperature-sensitive sauces and custards. Mauviel has been hammering copper in Normandy since 1830, and every M'Heritage piece carries that pedigree.",
    aspectRatio: 0.98,
    gumis: 41000,
    shares: 4510,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 23. KitchenAid Stand Mixer ───────────────────────
  {
    id: "kitchen-23",
    title: "Artisan Series 5 Qt Stand Mixer",
    brand: "KitchenAid",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
      alt: "Iconic stand mixer in pistachio green",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&q=80", alt: "Iconic stand mixer in pistachio green" },
      { url: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=1200&q=80", alt: "Mixer with dough hook attachment" },
    ],
    price: { min: 37999, max: 37999, currency: "USD" },
    rating: { average: 4.8, count: 4210 },
    buyUrl: "https://kitchenaid.com",
    topFeatures: ["10 Speed Settings", "59-Point Planetary Mixing", "5 Qt Stainless Bowl", "Tilt-Head Design", "Over 10 Optional Attachments"],
    description: "The kitchen icon that turns anyone into a baker. KitchenAid's Artisan mixer powers through bread dough and delicately whips meringue with equal ease, thanks to its 59-point planetary mixing action. Available in 50+ colors because it's a permanent countertop resident.",
    aspectRatio: 1.0,
    gumis: 58000,
    shares: 6380,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 24. Hasami Porcelain Espresso Cups ───────────────
  {
    id: "kitchen-24",
    title: "Espresso Cup & Saucer Set — Black",
    brand: "Hasami Porcelain",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=600&q=80",
      alt: "Minimalist black porcelain espresso cups",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=1200&q=80", alt: "Minimalist black porcelain espresso cups" },
      { url: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=1200&q=80", alt: "Espresso cups on saucers" },
    ],
    price: { min: 5600, max: 5600, currency: "USD" },
    rating: { average: 4.7, count: 318 },
    buyUrl: "https://hasami-porcelain.com",
    topFeatures: ["Set of 2 Cups & Saucers", "3 oz Capacity", "Stackable Design", "Microwave Safe", "Matte Exterior Finish"],
    description: "Espresso deserves a vessel that honors the ritual. Hasami's cups are precisely sized for a double shot, with a matte exterior that feels like silk and a glazed interior that cleans effortlessly. The saucers double as lids when stacked — brilliant Japanese design thinking.",
    aspectRatio: 0.72,
    gumis: 3800,
    shares: 418,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 25. Le Creuset Tea Kettle ────────────────────────
  {
    id: "kitchen-25",
    title: "Enamel on Steel Whistling Kettle",
    brand: "Le Creuset",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=600&q=80",
      alt: "Colorful enamel kettle on gas stove",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?w=1200&q=80", alt: "Colorful enamel kettle on gas stove" },
      { url: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=1200&q=80", alt: "Kettle pouring into teacup" },
    ],
    price: { min: 10000, max: 10000, currency: "USD" },
    rating: { average: 4.6, count: 1876 },
    buyUrl: "https://lecreuset.com",
    topFeatures: ["Carbon Steel with Enamel", "Single-Tone Whistle", "Cool-Touch Phenolic Handle", "1.7 Qt Capacity", "All Cooktops Including Induction"],
    description: "A stovetop kettle so beautiful you'll skip the electric option just to see it perched on the burner. Le Creuset's enamel-on-steel construction heats quickly and evenly, while the single-tone whistle is a surprisingly pleasant sound to start your morning.",
    aspectRatio: 1.12,
    gumis: 48000,
    shares: 5280,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 26. Zwilling Cheese Board Set ────────────────────
  {
    id: "kitchen-26",
    title: "Sommelier Cheese Board & Knife Set",
    brand: "Zwilling",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=600&q=80",
      alt: "Acacia cheese board with artisan cheeses",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=1200&q=80", alt: "Acacia cheese board with artisan cheeses" },
      { url: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1200&q=80", alt: "Cheese board styled for entertaining" },
    ],
    price: { min: 8900, max: 8900, currency: "USD" },
    rating: { average: 4.5, count: 567 },
    buyUrl: "https://zwilling.com",
    topFeatures: ["Acacia Hardwood Board", "3 Specialty Cheese Knives", "Hidden Drawer Storage", "16\" x 12\" Surface", "Magnetic Knife Closure"],
    description: "Every great cheese board starts with the actual board. Zwilling's acacia hardwood surface is generous enough for a full spread, with a hidden sliding drawer that stores three specialty knives — a fork, a spreader, and a chisel. Pull it out and you're instantly hosting.",
    aspectRatio: 0.82,
    gumis: 9400,
    shares: 940,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 27. Hedley & Bennett Bread Basket ────────────────
  {
    id: "kitchen-27",
    title: "Woven Cotton Bread Basket",
    brand: "Hedley & Bennett",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600&q=80",
      alt: "Artisan bread in woven cotton basket",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1200&q=80", alt: "Artisan bread in woven cotton basket" },
      { url: "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=1200&q=80", alt: "Basket on dinner table" },
    ],
    price: { min: 3800, max: 3800, currency: "USD" },
    rating: { average: 4.4, count: 201 },
    buyUrl: "https://hedleyandbennett.com",
    topFeatures: ["100% Cotton Construction", "Removable Linen Liner", "10\" Diameter", "Collapsible for Storage", "Machine Washable"],
    description: "There's something about warm bread arriving to the table in a proper basket that elevates the entire meal. Hedley & Bennett's cotton weave is sturdy enough to hold a full boule, with a removable linen liner that catches crumbs and goes straight in the wash.",
    aspectRatio: 0.92,
    gumis: 11200,
    shares: 1120,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 28. Material Kitchen Herb Scissors ───────────────
  {
    id: "kitchen-28",
    title: "5-Blade Herb Scissors",
    brand: "Material Kitchen",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=600&q=80",
      alt: "Sleek herb scissors with fresh basil",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=1200&q=80", alt: "Sleek herb scissors with fresh basil" },
      { url: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=1200&q=80", alt: "Scissors snipping chives" },
    ],
    price: { min: 1800, max: 1800, currency: "USD" },
    rating: { average: 4.3, count: 654 },
    buyUrl: "https://materialkitchen.com",
    topFeatures: ["5 Stainless Steel Blades", "Silicone-Grip Handle", "Cleaning Comb Included", "Dishwasher Safe", "8.5\" Length"],
    description: "Five blades do the work in one snip that would take a knife five passes. Material's herb scissors make fast, uniform work of basil, chives, cilantro, and anything else you'd rather not bruise with a blade. The included cleaning comb pops right between the blades.",
    aspectRatio: 1.42,
    gumis: 14500,
    shares: 1450,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 29. Emile Henry Butter Dish ──────────────────────
  {
    id: "kitchen-29",
    title: "Butter Dish with Lid — Burgundy",
    brand: "Emile Henry",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&q=80",
      alt: "Ceramic butter dish with lid on marble counter",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=1200&q=80", alt: "Ceramic butter dish with lid on marble counter" },
      { url: "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=1200&q=80", alt: "Butter dish at breakfast table" },
    ],
    price: { min: 3200, max: 3200, currency: "USD" },
    rating: { average: 4.5, count: 412 },
    buyUrl: "https://emilehenryusa.com",
    topFeatures: ["HR Ceramic", "Holds Standard Butter Stick", "Integrated Lid", "Made in France", "Dishwasher & Microwave Safe"],
    description: "Life is too short for cold, hard butter. Emile Henry's ceramic dish keeps butter at perfect spreading temperature on the counter, protected by a snug-fitting lid. The Burgundy glaze is a nod to the French region where these have been made for over 170 years.",
    aspectRatio: 0.65,
    gumis: 22000,
    shares: 2200,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 30. Zwilling Pepper Mill ─────────────────────────
  {
    id: "kitchen-30",
    title: "Enfinigy Electric Pepper Mill",
    brand: "Zwilling",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=600&q=80",
      alt: "Sleek electric pepper mill in brushed steel",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?w=1200&q=80", alt: "Sleek electric pepper mill in brushed steel" },
      { url: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=1200&q=80", alt: "Pepper mill at dinner table" },
    ],
    price: { min: 4900, max: 4900, currency: "USD" },
    rating: { average: 4.4, count: 734 },
    buyUrl: "https://zwilling.com",
    topFeatures: ["Ceramic Grinding Mechanism", "Adjustable Coarseness", "LED Light for Precision", "Rechargeable Battery", "Brushed Stainless Steel"],
    description: "One-handed freshly ground pepper, directed by a built-in LED light so you can see exactly where it lands. Zwilling's ceramic mechanism never dulls and won't corrode, while the rechargeable battery means you'll never hunt for AAAs mid-recipe again.",
    aspectRatio: 1.52,
    gumis: 87000,
    shares: 8700,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 31. Our Place Perfect Pot ────────────────────────
  {
    id: "kitchen-31",
    title: "Perfect Pot 5.5 Qt",
    brand: "Our Place",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=600&q=80",
      alt: "Sage green ceramic coated pot with colander lid",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=1200&q=80", alt: "Sage green ceramic coated pot with colander lid" },
      { url: "https://images.unsplash.com/photo-1507914372368-b2b085b925a1?w=1200&q=80", alt: "Perfect Pot cooking pasta" },
      { url: "https://images.unsplash.com/photo-1497888329096-51c27beff665?w=1200&q=80", alt: "Pot at styled dinner table" },
    ],
    price: { min: 16500, max: 16500, currency: "USD" },
    rating: { average: 4.6, count: 2187 },
    buyUrl: "https://fromourplace.com",
    topFeatures: ["Replaces 6 Pieces of Cookware", "Built-In Colander Lid", "Toxin-Free Ceramic Coating", "Roasting Rack Included", "5.5 Qt Capacity"],
    description: "The companion to the Always Pan, designed to replace your stockpot, Dutch oven, saucepot, roasting rack, colander, and steamer. The built-in colander lid is a stroke of genius — drain pasta without reaching for another tool. It's the pot that actually simplifies cooking.",
    aspectRatio: 0.95,
    gumis: 18500,
    shares: 1850,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 32. Heath Ceramics Stoneware Mug ─────────────────
  {
    id: "kitchen-32",
    title: "Large Mug — Redwood",
    brand: "Heath Ceramics",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1507914372368-b2b085b925a1?w=600&q=80",
      alt: "Hand-thrown stoneware mug in warm red glaze",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1507914372368-b2b085b925a1?w=1200&q=80", alt: "Hand-thrown stoneware mug in warm red glaze" },
      { url: "https://images.unsplash.com/photo-1497888329096-51c27beff665?w=1200&q=80", alt: "Mug with latte art" },
    ],
    price: { min: 4200, max: 4200, currency: "USD" },
    rating: { average: 4.7, count: 543 },
    buyUrl: "https://heathceramics.com",
    topFeatures: ["Handmade in San Francisco", "Reactive Glaze Finish", "12 oz Capacity", "Lead-Free", "Thick Comfortable Handle"],
    description: "Each Heath mug is shaped by hand in their Sausalito studio and finished with a reactive glaze that shifts and pools uniquely on every piece. The generous 12 oz size is perfect for a proper pour, and the thick handle feels reassuring in early-morning hands.",
    aspectRatio: 0.76,
    gumis: 16200,
    shares: 1620,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 33. GreenPan Reserve Skillet ─────────────────────
  {
    id: "kitchen-33",
    title: "Reserve Ceramic Nonstick 12\" Skillet",
    brand: "GreenPan",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1497888329096-51c27beff665?w=600&q=80",
      alt: "Cream ceramic nonstick skillet on burner",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1497888329096-51c27beff665?w=1200&q=80", alt: "Cream ceramic nonstick skillet on burner" },
      { url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&q=80", alt: "Skillet with sunny-side eggs" },
    ],
    price: { min: 9000, max: 9000, currency: "USD" },
    rating: { average: 4.5, count: 1345 },
    buyUrl: "https://greenpan.us",
    topFeatures: ["Thermolon Infinity Ceramic Coating", "Hard Anodized Body", "Stainless Steel Handle", "Oven Safe to 600F", "PFAS & PFOA Free"],
    description: "Nonstick that you can feel good about. GreenPan pioneered healthy ceramic coating, and the Reserve line takes it further with Thermolon Infinity — their most durable surface yet. Sear at high heat, deglaze confidently, and slide an omelette out without a trace of oil.",
    aspectRatio: 1.08,
    gumis: 24500,
    shares: 2450,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 34. Fellow Atmos Vacuum Canister ─────────────────
  {
    id: "kitchen-34",
    title: "Atmos Vacuum Canister — Matte Black",
    brand: "Fellow",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
      alt: "Matte black vacuum canister with coffee beans",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&q=80", alt: "Matte black vacuum canister with coffee beans" },
      { url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1200&q=80", alt: "Canister on kitchen shelf" },
    ],
    price: { min: 3400, max: 4000, currency: "USD" },
    rating: { average: 4.6, count: 1123 },
    buyUrl: "https://fellowproducts.com",
    topFeatures: ["Integrated Vacuum Pump", "Airtight Silicone Seal", "BPA-Free Container", "Twist-Lock Lid", "0.7L or 1.2L Sizes"],
    description: "Your beans start going stale the moment they're roasted — Fellow's Atmos fights back with an integrated vacuum pump that removes air with a simple twist. The result is coffee that tastes days-fresh for weeks. The matte black finish makes it the handsomest thing in the pantry.",
    aspectRatio: 1.25,
    gumis: 12800,
    shares: 1280,
    gumiedByFriends: getRandomGumiFriends(),
  },
  // ─── 35. Riedel Decanter ──────────────────────────────
  {
    id: "kitchen-35",
    title: "Amadeo Lyra Decanter",
    brand: "Riedel",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80",
      alt: "Sculptural crystal wine decanter",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=1200&q=80", alt: "Sculptural crystal wine decanter" },
      { url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&q=80", alt: "Decanter with red wine on table" },
      { url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=1200&q=80", alt: "Decanter detail shot" },
    ],
    price: { min: 32500, max: 32500, currency: "USD" },
    rating: { average: 4.9, count: 187 },
    buyUrl: "https://riedel.com",
    topFeatures: ["Mouth-Blown Crystal", "Lyre-Shaped Design", "Maximizes Aeration Surface", "1500ml Capacity", "Handcrafted in Austria"],
    description: "More sculpture than barware, Riedel's Amadeo Lyra is mouth-blown by master craftsmen into a shape that maximizes wine-to-air contact for rapid aeration. Pour in a young Barolo and watch it open up in minutes rather than hours. The kind of piece that starts conversations before the wine does.",
    aspectRatio: 1.38,
    gumis: 12800,
    shares: 1280,
    gumiedByFriends: getRandomGumiFriends(),
  },
];
